-- V0009 contract v1.1 changes to the shipped v1a tables (row N-006). Contract 855b7e0 added three business code
-- lists (channel, sub_channel, geo_class) and 54 config keys of docs/24 s9.5 (programmes, content, field app
-- details, back office), and two risk signals whose weights extend cfg.geo.integrity_weight. V0005 and V0006 are
-- shipped and never edited, so the changes land here.

ALTER TABLE app.code_list DROP CONSTRAINT code_list_list_key_check;
ALTER TABLE app.code_list ADD CONSTRAINT code_list_list_key_check CHECK (list_key IN (
  'channel','sub_channel','geo_class','force_reason','edit_reason','void_reason','visit_outcome','skip_reason',
  'day_exception_reason','stock_variance_reason','task_type','leave_type','feedback_category','qc_fault_type',
  'payment_mode','outlet_close_reason','submit_void_reason'));
INSERT INTO app.code_list (list_key) VALUES ('channel'), ('sub_channel'), ('geo_class');

-- Config keys added or changed by contract v1.1 (docs/24 s9.5 at 855b7e0), generated like V0006. cfg.app.home_tiles and
-- cfg.web.menu_by_role default to {} until their seed matrices are written (docs/requests/db-config-matrices.md).
INSERT INTO app.cfg_key (key, area, kind, value_type, default_value, bounds, bounds_rule, scope_levels, risk_class, risk_rule, effect, delivery, requires_ack, future_dated_only, editor_permission, description_en) VALUES
  ('cfg.loyalty.program_active', 'loyalty', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'wing', 'division', 'territory']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.loyalty.earning_rules', 'loyalty', 'S', 'json', '{"posm_survey_photo": {"points": 50, "once_per": "survey_response"}, "amo_survey": {"points": 0}}'::jsonb, '{}'::jsonb, 'points 0..100000', ARRAY['global', 'wing']::text[], 3, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.loyalty.expiry_days', 'loyalty', 'S', 'int', '7'::jsonb, '{"min": 0, "max": 365}'::jsonb, NULL, ARRAY['global']::text[], 3, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.loyalty.cash_rate_mtk_per_point', 'loyalty', 'S', 'money_mtk', '2000'::jsonb, '{"min": 0, "max": 100000}'::jsonb, NULL, ARRAY['global', 'wing']::text[], 3, NULL, 'B', 'both', true, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.loyalty.cash_max_points', 'loyalty', 'S', 'int', '199'::jsonb, '{"min": 0, "max": 100000}'::jsonb, NULL, ARRAY['global', 'wing']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.loyalty.redemption_requires_photo', 'loyalty', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.loyalty.redemption_roles', 'loyalty', 'S', 'list', '["SR", "AMO"]'::jsonb, '{}'::jsonb, 'subset of roles', ARRAY['global']::text[], 1, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.loyalty.negative_balance_policy', 'loyalty', 'S', 'enum', '"accept_and_flag"'::jsonb, '{"enum": ["accept_and_flag", "reject"]}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.astha.program_active', 'astha', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'wing']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.astha.quarter_start_month', 'astha', 'S', 'int', '1'::jsonb, '{"min": 1, "max": 12}'::jsonb, NULL, ARRAY['global']::text[], 3, NULL, 'S', 'both', false, true, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.astha.target_entry_roles', 'astha', 'S', 'list', '["ADMIN", "TSO"]'::jsonb, '{}'::jsonb, 'subset of roles', ARRAY['global']::text[], 2, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.astha.gift_choice_roles', 'astha', 'S', 'list', '["TSO"]'::jsonb, '{}'::jsonb, 'subset of roles', ARRAY['global']::text[], 1, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.astha.gift_choice_lock', 'astha', 'S', 'enum', '"on_sr_photo"'::jsonb, '{"enum": ["none", "on_sr_photo"]}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.astha.one_photo_per_outlet', 'astha', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.superstar.program_active', 'superstar', 'S', 'bool', 'false'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'wing']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.superstar.criteria_met_rule', 'superstar', 'S', 'json', '{"std_pct": 100, "memo_pct": 100}'::jsonb, '{"min": 0, "max": 200}'::jsonb, 'each', ARRAY['global', 'wing']::text[], 2, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.content.max_item_mb', 'content', 'S', 'int', '8'::jsonb, '{"min": 1, "max": 20}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.ops', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.content.download_network_policy', 'content', 'S', 'enum', '"wifi_only"'::jsonb, '{"enum": ["wifi_only", "wifi_preferred", "any"]}'::jsonb, NULL, ARRAY['global', 'wing']::text[], 2, NULL, 'B', 'device', false, false, 'cfg.edit.ops', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.flag.loyalty_ui', 'flag', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'role', 'wing', 'division', 'territory', 'zone', 'user', 'device']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.release', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.flag.astha_ui', 'flag', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'role', 'wing', 'division', 'territory', 'zone', 'user', 'device']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.release', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.flag.superstar_ui', 'flag', 'S', 'bool', 'false'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'role', 'wing', 'division', 'territory', 'zone', 'user', 'device']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.release', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.flag.print_enabled', 'flag', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'role', 'wing', 'division', 'territory', 'zone', 'user', 'device']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.release', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.flag.credit_ui', 'flag', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'role', 'wing', 'division', 'territory', 'zone', 'user', 'device']::text[], 2, NULL, 'B', 'both', false, false, 'cfg.edit.release', 'Programmes and content (docs/24 s9.5)'),
  ('cfg.app.home_tiles', 'app', 'S', 'json', '{}'::jsonb, '{}'::jsonb, 'must keep Attendance, Sale, Memo, Sales Submit', ARRAY['global', 'role', 'user']::text[], 1, NULL, 'B', 'device', false, false, 'cfg.edit.ops', 'Field app details (docs/24 s9.5)'),
  ('cfg.app.activity_log_sample_pct', 'app', 'S', 'pct', '10'::jsonb, '{"min": 0, "max": 100}'::jsonb, NULL, ARRAY['global', 'role']::text[], 1, NULL, 'B', 'device', false, false, 'cfg.edit.ops', 'Field app details (docs/24 s9.5)'),
  ('cfg.app.location_notice_required', 'app', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'device', false, false, 'cfg.edit.security', 'Field app details (docs/24 s9.5)'),
  ('cfg.sale.sort_by_distance', 'sale', 'S', 'bool', 'false'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'role']::text[], 0, NULL, 'B', 'device', false, false, 'cfg.edit.field', 'Field app details (docs/24 s9.5)'),
  ('cfg.sale.suggested_qty_enabled', 'sale', 'S', 'bool', 'false'::jsonb, '{}'::jsonb, NULL, ARRAY['global', 'wing', 'territory']::text[], 1, NULL, 'B', 'both', false, false, 'cfg.edit.programme', 'Field app details (docs/24 s9.5)'),
  ('cfg.stock.resave_guard_window_min', 'stock', 'S', 'int', '5'::jsonb, '{"min": 1, "max": 60}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'both', false, false, 'cfg.edit.ops', 'Field app details (docs/24 s9.5)'),
  ('cfg.visit.closed_streak_task', 'visit', 'S', 'int', '3'::jsonb, '{"min": 0, "max": 10}'::jsonb, '0 = off', ARRAY['global', 'wing']::text[], 1, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Field app details (docs/24 s9.5)'),
  ('cfg.calendar.weekend_days', 'calendar', 'S', 'list', '[5]'::jsonb, '{"max_items": 3}'::jsonb, '0..3 days', ARRAY['global', 'wing', 'division']::text[], 3, NULL, 'S', 'both', false, true, 'cfg.edit.field', 'Field app details (docs/24 s9.5)'),
  ('cfg.day.take_action_after', 'day', 'S', 'time', '"17:00"'::jsonb, '{}'::jsonb, '12:00..23:00', ARRAY['global', 'wing']::text[], 1, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Field app details (docs/24 s9.5)'),
  ('cfg.tso.periphery_radius_options_m', 'tso', 'S', 'list', '[50, 100, 300]'::jsonb, '{"max_items": 6}'::jsonb, '1..6 values, 10..5000', ARRAY['global', 'wing']::text[], 0, NULL, 'B', 'both', false, false, 'cfg.edit.field', 'Field app details (docs/24 s9.5)'),
  ('cfg.tso.periphery_max_markers', 'tso', 'S', 'int', '300'::jsonb, '{"min": 50, "max": 2000}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'both', false, false, 'cfg.edit.ops', 'Field app details (docs/24 s9.5)'),
  ('cfg.support.max_upload_mb', 'support', 'S', 'int', '20'::jsonb, '{"min": 5, "max": 100}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'device', false, false, 'cfg.edit.ops', 'Field app details (docs/24 s9.5)'),
  ('cfg.support.pda_upload_wifi_only', 'support', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'device', false, false, 'cfg.edit.ops', 'Field app details (docs/24 s9.5)'),
  ('cfg.web.entry_backdate_days', 'web', 'S', 'int', '0'::jsonb, '{"min": 0, "max": 31}'::jsonb, NULL, ARRAY['global', 'zone']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Back office (docs/24 s9.5)'),
  ('cfg.web.entry_classes', 'web', 'S', 'list', '["GT"]'::jsonb, '{}'::jsonb, 'subset of sub-channels', ARRAY['global', 'zone']::text[], 1, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Back office (docs/24 s9.5)'),
  ('cfg.web.entry_validate_calls_le_target', 'web', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Back office (docs/24 s9.5)'),
  ('cfg.web.entry_app_overlap_policy', 'web', 'S', 'enum', '"exclusive_flag"'::jsonb, '{"enum": ["exclusive_flag", "replace", "add"]}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Back office (docs/24 s9.5)'),
  ('cfg.web.entry_unlock_roles', 'web', 'S', 'list', '["SUPPORT", "ADMIN"]'::jsonb, '{}'::jsonb, 'subset of roles', ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.security', 'Back office (docs/24 s9.5)'),
  ('cfg.web.entry_unlock_max_days', 'web', 'S', 'int', '7'::jsonb, '{"min": 1, "max": 31}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.security', 'Back office (docs/24 s9.5)'),
  ('cfg.web.entry_unlock_ttl_h', 'web', 'S', 'int', '24'::jsonb, '{"min": 1, "max": 168}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.security', 'Back office (docs/24 s9.5)'),
  ('cfg.web.menu_by_role', 'web', 'S', 'json', '{}'::jsonb, '{}'::jsonb, 'menu ids from the page registry', ARRAY['role']::text[], 3, NULL, 'B', 'server', false, false, 'cfg.edit.security', 'Back office (docs/24 s9.5)'),
  ('cfg.entry.paper_backfill_window_days', 'entry', 'S', 'int', '7'::jsonb, '{"min": 1, "max": 30}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Back office (docs/24 s9.5)'),
  ('cfg.target.approval_levels', 'target', 'S', 'json', '[{"level": 1, "role": "WM"}]'::jsonb, '{"min": 1, "max": 5}'::jsonb, 'levels', ARRAY['global', 'wing']::text[], 3, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Back office (docs/24 s9.5)'),
  ('cfg.target.lock_after_month_start', 'target', 'S', 'bool', 'true'::jsonb, '{}'::jsonb, NULL, ARRAY['global']::text[], 3, NULL, 'S', 'server', false, false, 'cfg.edit.security', 'Back office (docs/24 s9.5)'),
  ('cfg.target.template_version', 'target', 'S', 'int', '1'::jsonb, '{"min": 1, "max": 999}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Back office (docs/24 s9.5)'),
  ('cfg.target.upload_max_rows', 'target', 'S', 'int', '12000'::jsonb, '{"min": 100, "max": 50000}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'S', 'server', false, false, 'cfg.edit.programme', 'Back office (docs/24 s9.5)'),
  ('cfg.price.max_change_pct', 'price', 'S', 'pct', '15'::jsonb, '{"min": 1, "max": 100}'::jsonb, NULL, ARRAY['global']::text[], 2, NULL, 'B', 'server', false, false, 'cfg.edit.finance', 'Back office (docs/24 s9.5)'),
  ('cfg.geo.density_neighbour_radii_m', 'geo', 'S', 'list', '[25, 50, 100, 150, 300]'::jsonb, '{"max_items": 8}'::jsonb, '1..8 values, 10..1000', ARRAY['global']::text[], 1, NULL, 'B', 'server', false, false, 'cfg.edit.ops', 'Back office (docs/24 s9.5)'),
  ('cfg.geo.calibration_min_visits', 'geo', 'S', 'int', '500'::jsonb, '{"min": 100, "max": 5000}'::jsonb, NULL, ARRAY['global']::text[], 1, NULL, 'B', 'server', false, false, 'cfg.edit.field', 'Back office (docs/24 s9.5)'),
  ('cfg.sys.break_glass_mode', 'sys', 'S', 'enum', '"restore_or_restrict_only"'::jsonb, '{"enum": ["restore_or_restrict_only", "restore_only", "off"]}'::jsonb, NULL, ARRAY['global']::text[], 3, NULL, 'B', 'server', false, false, 'cfg.edit.security', 'Back office (docs/24 s9.5)'),
  ('cfg.sys.break_glass_max_h', 'sys', 'S', 'int', '4'::jsonb, '{"min": 1, "max": 8}'::jsonb, NULL, ARRAY['global']::text[], 3, NULL, 'B', 'server', false, false, 'cfg.edit.security', 'Back office (docs/24 s9.5)');

UPDATE app.cfg_key SET area = 'geo', kind = 'S', value_type = 'json', default_value = '{"GEO_MOCK": 100, "GEO_TELEPORT": 40, "GEO_ZERO_JITTER": 40, "GEO_PERFECT_ACCURACY": 20, "GEO_SAME_POINT": 30, "GEO_ROUTE_SINGLE_POINT": 40, "GEO_STALE_FIX": 20, "GEO_GNSS_INCONSISTENT": 30, "GEO_GNSS_TIME_SKEW": 30, "GEO_DEVICE_SERVER_MISMATCH": 40, "GEO_SHORT_VISIT_GAPS": 20, "DEVICE_NOT_OWNER": 60, "DEVICE_INTEGRITY_FAIL": 30, "DEVICE_DEBUG_ENABLED": 10, "DEVICE_MOCK_APP_PRESENT": 30, "DEVICE_POLICY_DRIFT": 10, "CLOCK_SKEW": 10, "GEO_OUT_OF_BOUNDS": 40, "CONFIG_STAMP_REGRESS": 20}'::jsonb, bounds = '{}'::jsonb, bounds_rule = 'each 0..300', scope_levels = ARRAY['global']::text[], risk_class = 2, risk_rule = NULL, effect = 'B', delivery = 'server', requires_ack = false, future_dated_only = false, editor_permission = 'cfg.edit.security', description_en = 'Geofence and location (docs/24 s9.5)', updated_at = now() WHERE key = 'cfg.geo.integrity_weight';
