#!/usr/bin/env python3
"""Generates backend/sync/.../PayloadShapes.kt from contract/slices (record payload member names and required members).
Run from the repo root: python3 backend/sync/tools/gen_payload_shapes.py. PayloadShapesDriftTest fails when the output
differs from the checked-in file."""
import sys, yaml, pathlib
S = pathlib.Path('contract/slices/schemas')
def load(n): return yaml.safe_load((S / f'{n}.yaml').read_text())[n]
def merged(d):
    if '$ref' in d: return merged(load(d['$ref'].split('/')[-1]))
    props, req = {}, list(d.get('required', []))
    for x in d.get('allOf', []):
        p, r = merged(x); props.update(p); req += r
    props.update(d.get('properties', {}))
    return props, req
rec = load('SyncRecord')['discriminator']['mapping']
lines = []
for typ in sorted(rec):
    rname = rec[typ].split('/')[-1]
    props, _ = merged(load(rname))
    pref = props['payload'].get('$ref', '').split('/')[-1]
    p, r = merged(load(pref))
    nested = {}
    for k, v in sorted(p.items()):
        ref = v.get('$ref', '').split('/')[-1]
        if not ref:
            for alt in v.get('oneOf', []) + v.get('anyOf', []):
                if '$ref' in alt: ref = alt['$ref'].split('/')[-1]
        if ref:
            sd = load(ref)
            # A map (propertyNames/additionalProperties, no properties: TypeCounts) has no fixed member list.
            if 'properties' in sd or 'allOf' in sd:
                np_, nr = merged(sd); nested[k] = (sorted(np_), sorted(set(nr)))
    def kl(xs): return 'setOf(' + ', '.join(f'"{x}"' for x in xs) + ')'
    nest = ', '.join(f'"{k}" to Shape({kl(a)}, {kl(b)})' for k, (a, b) in sorted(nested.items()))
    lines.append(f'        "{typ}" to PayloadShape({kl(sorted(p))}, {kl(sorted(set(r)))}, mapOf({nest})),')
env_p, env_r = merged(load('RecordEnvelope'))
out = f'''package com.aktcl.aron.backend.sync

// GENERATED by backend/sync/tools/gen_payload_shapes.py from contract/slices. Do not edit; PayloadShapesDriftTest guards it.

/** Member names of an object schema and the required ones. */
data class Shape(val allowed: Set<String>, val required: Set<String>)

/** A record payload: its members, the required ones, and the members that are objects with a known shape. */
data class PayloadShape(val allowed: Set<String>, val required: Set<String>, val nested: Map<String, Shape>)

object PayloadShapes {{
    /** Envelope members (docs/24 s4.3), `payload` included. */
    val ENVELOPE: Shape = Shape(setOf({', '.join(f'"{x}"' for x in sorted(set(env_p) | {'payload'}))}), setOf({', '.join(f'"{x}"' for x in sorted(set(env_r)))}))

    val BY_TYPE: Map<String, PayloadShape> = mapOf(
{chr(10).join(lines)}
    )
}}
'''
dest = pathlib.Path('backend/sync/src/main/kotlin/com/aktcl/aron/backend/sync/PayloadShapes.kt')
if len(sys.argv) > 1 and sys.argv[1] == '--check':
    sys.exit(0 if dest.read_text() == out else 1)
dest.write_text(out)
