// Aliases over the GENERATED contract types (openapi.d.ts, never edited by hand: `npm run gen:contract`).
// Everything in the web app takes its wire types from here so a contract rename breaks `tsc` (docs/24 s1.3).
import type { components, paths } from "./openapi";

export type { components, paths };
export type Schemas = components["schemas"];

export type Role = Schemas["Role"];
export type UserSummary = Schemas["UserSummary"];
export type ScopeSummary = Schemas["ScopeSummary"];
export type NodeRef = Schemas["NodeRef"];
export type LoginRequest = Schemas["LoginRequest"];
export type LoginResponse = Schemas["LoginResponse"];
export type TokenPair = Schemas["TokenPair"];
export type MfaVerifyRequest = Schemas["MfaVerifyRequest"];
export type Me = Schemas["Me"];
export type Problem = Schemas["Problem"];
export type ProblemCode = Schemas["ProblemCode"];
export type AuditEntry = Schemas["AuditEntry"];
export type AuditPage = Schemas["AuditPage"];
export type Cluster = Schemas["Cluster"];
export type ClusterWrite = Schemas["ClusterWrite"];
export type ClusterPatch = Schemas["ClusterPatch"];
export type ClusterPage = Schemas["ClusterPage"];

export type ApiPath = keyof paths;
export type GeoNode = Schemas["GeoNode"];
export type GeoNodeWrite = Schemas["GeoNodeWrite"];
export type GeoNodePatch = Schemas["GeoNodePatch"];
export type GeoLevel = Schemas["GeoLevel"];
export type Route = Schemas["Route"];
export type RouteWrite = Schemas["RouteWrite"];
export type RoutePatch = Schemas["RoutePatch"];
export type RouteAssignment = Schemas["RouteAssignment"];
export type RouteAssignmentWrite = Schemas["RouteAssignmentWrite"];
export type EndAssignmentRequest = Schemas["EndAssignmentRequest"];
export type User = Schemas["User"];
export type UserWrite = Schemas["UserWrite"];
export type UserPatch = Schemas["UserPatch"];
export type CredentialActionRequest = Schemas["CredentialActionRequest"];
export type ProductNode = Schemas["ProductNode"];
export type ProductNodeWrite = Schemas["ProductNodeWrite"];
export type ProductNodePatch = Schemas["ProductNodePatch"];
export type ProductTreeLevel = Schemas["ProductTreeLevel"];
export type Sku = Schemas["Sku"];
export type SkuWrite = Schemas["SkuWrite"];
export type SkuPatch = Schemas["SkuPatch"];
export type Holiday = Schemas["Holiday"];
export type HolidayWrite = Schemas["HolidayWrite"];
export type CodeItem = Schemas["CodeItem"];
export type CodeList = Schemas["CodeList"];
export type CodeListKey = Schemas["CodeListKey"];
export type CodeListWrite = Schemas["CodeListWrite"];
export type Outlet = Schemas["Outlet"];
export type OutletWrite = Schemas["OutletWrite"];
export type OutletPatch = Schemas["OutletPatch"];
export type OutletKindBulkWrite = Schemas["OutletKindBulkWrite"];
export type OutletRequestSummary = Schemas["OutletRequestSummary"];
export type OutletRequestVerifyRequest = Schemas["OutletRequestVerifyRequest"];
export type OutletRequestApproveRequest = Schemas["OutletRequestApproveRequest"];
export type Feedback = Schemas["Feedback"];
export type FeedbackStatusWrite = Schemas["FeedbackStatusWrite"];
export type ReasonRequest = Schemas["ReasonRequest"];
