ConfigVersionDetail:
  type: object
  required:
  - config_version
  - committed_at
  - values
  additionalProperties: false
  properties:
    config_version:
      $ref: '#/components/schemas/ConfigVersionNumber'
    committed_at:
      $ref: '#/components/schemas/Timestamp'
    change_id:
      type:
      - integer
      - 'null'
      format: int64
      minimum: 1
    values:
      type: array
      maxItems: 1000
      items:
        $ref: '#/components/schemas/ResolvedConfigValue'
