// GENERATED by shared/contract/tools/gen_wire_dtos.py from contract/slices/schemas (source of truth: contract/openapi.yaml).
// Do not edit by hand: change the contract, regenerate the slices (tools/slice-contract.py) and re-run the generator.
// WireDtosDriftTest compares every member here with the slice fields (name, required, nullable, JSON type).
package com.aktcl.aron.contract

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

// ---- Auth (docs/24 s5) ----

@Serializable
data class LoginRequest(
    @SerialName("username") val username: String,
    @SerialName("password") val password: String,
    @SerialName("client") val client: String,
    @SerialName("device_uuid") val deviceUuid: String? = null,
)

@Serializable
data class LoginResponse(
    @SerialName("status") val status: String,
    @SerialName("access_token") val accessToken: String? = null,
    @SerialName("access_expires_at") val accessExpiresAt: String? = null,
    @SerialName("refresh_token") val refreshToken: String? = null,
    @SerialName("refresh_expires_at") val refreshExpiresAt: String? = null,
    @SerialName("upload_refresh_token") val uploadRefreshToken: String? = null,
    @SerialName("bind_token") val bindToken: String? = null,
    @SerialName("mfa_token") val mfaToken: String? = null,
    @SerialName("user") val user: UserSummary,
    @SerialName("scope") val scope: ScopeSummary? = null,
    @SerialName("device") val device: LoginDevice? = null,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("server_time") val serverTime: String,
    @SerialName("min_app_version_code") val minAppVersionCode: Int? = null,
)

@Serializable
data class UserSummary(
    @SerialName("user_id") val userId: Long,
    @SerialName("username") val username: String,
    @SerialName("full_name") val fullName: String,
    @SerialName("role") val role: String,
    @SerialName("designation") val designation: String? = null,
    @SerialName("locale") val locale: String,
)

@Serializable
data class ScopeSummary(
    @SerialName("scope_version") val scopeVersion: Int,
    @SerialName("nodes") val nodes: List<NodeRef>,
)

@Serializable
data class NodeRef(
    @SerialName("type") val type: String,
    @SerialName("id") val id: Long,
    @SerialName("code") val code: String? = null,
    @SerialName("name") val name: String? = null,
)

@Serializable
data class LoginDevice(
    @SerialName("device_id") val deviceId: Long,
    @SerialName("bind_ordinal") val bindOrdinal: Int?,
    @SerialName("memo_seq_block_size") val memoSeqBlockSize: Int,
)

@Serializable
data class RefreshRequest(
    @SerialName("refresh_token") val refreshToken: String? = null,
    @SerialName("grant") val grant: String,
    @SerialName("device_uuid") val deviceUuid: String? = null,
)

@Serializable
data class TokenPair(
    @SerialName("access_token") val accessToken: String,
    @SerialName("access_expires_at") val accessExpiresAt: String,
    @SerialName("refresh_token") val refreshToken: String? = null,
    @SerialName("refresh_expires_at") val refreshExpiresAt: String,
    @SerialName("scope_version") val scopeVersion: Int,
    @SerialName("server_time") val serverTime: String,
)

@Serializable
data class LogoutRequest(
    @SerialName("scope") val scope: String,
    @SerialName("refresh_token") val refreshToken: String? = null,
)

// ---- Bundle (docs/24 s3.6) ----

@Serializable
data class PagedSection(
    @SerialName("section") val section: String,
    @SerialName("pages") val pages: Int,
    @SerialName("rows") val rows: Int,
)

@Serializable
data class BundleMeta(
    @SerialName("bundle_version") val bundleVersion: String,
    @SerialName("valid_for_business_date") val validForBusinessDate: String,
    @SerialName("generated_at") val generatedAt: String,
    @SerialName("server_time") val serverTime: String,
    @SerialName("user_id") val userId: Long,
    @SerialName("role") val role: String,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("schema_version") val schemaVersion: Int,
    @SerialName("cursor") val cursor: String,
    @SerialName("is_prefetch") val isPrefetch: Boolean? = null,
    @SerialName("paged_sections") val pagedSections: List<PagedSection>,
)

@Serializable
data class BundleUser(
    @SerialName("user_id") val userId: Long,
    @SerialName("username") val username: String,
    @SerialName("full_name") val fullName: String,
    @SerialName("role") val role: String,
    @SerialName("designation") val designation: String? = null,
    @SerialName("locale") val locale: String,
    @SerialName("bind_ordinal") val bindOrdinal: Int,
    @SerialName("memo_seq_block_size") val memoSeqBlockSize: Int,
    @SerialName("zone_id") val zoneId: Long? = null,
    @SerialName("territory_id") val territoryId: Long? = null,
)

@Serializable
data class Route(
    @SerialName("created_at") val createdAt: String,
    @SerialName("updated_at") val updatedAt: String,
    @SerialName("version") val version: Int,
    @SerialName("id") val id: Long,
    @SerialName("code") val code: String,
    @SerialName("name") val name: String,
    @SerialName("display_label") val displayLabel: String? = null,
    @SerialName("zone_id") val zoneId: Long,
    @SerialName("kind") val kind: String,
    @SerialName("visit_kind") val visitKind: String? = null,
    @SerialName("visit_days_mask") val visitDaysMask: Int,
    @SerialName("sequence_no") val sequenceNo: Int? = null,
    @SerialName("status") val status: String,
)

/** Per-route section of the bundle; replaced as a whole when the route is added to the user. */
@Serializable
data class RouteSnapshot(
    @SerialName("route_id") val routeId: Long,
    @SerialName("route_snapshot_version") val routeSnapshotVersion: Int,
    @SerialName("route") val route: Route,
    @SerialName("assignment_kind") val assignmentKind: String,
    @SerialName("acting_for_user_id") val actingForUserId: Long? = null,
    @SerialName("planned_today") val plannedToday: Boolean,
    @SerialName("target_outlets") val targetOutlets: Int,
    @SerialName("outlets") val outlets: List<BundleOutlet>,
    @SerialName("open_memos") val openMemos: List<OpenMemo>,
    @SerialName("sales_plan_sku_ids") val salesPlanSkuIds: List<Long>,
    @SerialName("targets") val targets: List<JsonElement>,
    @SerialName("achievement_mtd") val achievementMtd: List<JsonElement>,
    @SerialName("day_state") val dayState: JsonElement,
)

/** Outlet as the phone needs it. `radius_m` and `max_accuracy_m` are already resolved for this outlet (outlet > route > zone > geo_class > territory > division > wing > global). */
@Serializable
data class BundleOutlet(
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("route_id") val routeId: Long,
    @SerialName("code") val code: String,
    @SerialName("name") val name: String,
    @SerialName("name_bn") val nameBn: String? = null,
    @SerialName("name_sort_key") val nameSortKey: String,
    @SerialName("owner_name") val ownerName: String,
    @SerialName("contact_number") val contactNumber: String? = null,
    @SerialName("lat") val lat: Double? = null,
    @SerialName("lng") val lng: Double? = null,
    @SerialName("location_confirmed") val locationConfirmed: Boolean,
    @SerialName("provisional_lat") val provisionalLat: Double? = null,
    @SerialName("provisional_lng") val provisionalLng: Double? = null,
    @SerialName("cluster_id") val clusterId: Long,
    @SerialName("cluster_name") val clusterName: String,
    @SerialName("channel") val channel: String,
    @SerialName("sub_channel_id") val subChannelId: Long? = null,
    @SerialName("geo_class") val geoClass: String? = null,
    @SerialName("status") val status: String,
    @SerialName("price_type") val priceType: String,
    @SerialName("outlet_kind") val outletKind: String,
    @SerialName("radius_m") val radiusM: Int,
    @SerialName("max_accuracy_m") val maxAccuracyM: Int,
    @SerialName("visit_sequence") val visitSequence: Int? = null,
    @SerialName("open_due_mtk") val openDueMtk: Long,
    @SerialName("open_due_as_of") val openDueAsOf: String? = null,
    @SerialName("programme_flags") val programmeFlags: List<String>,
    @SerialName("pending_request") val pendingRequest: Boolean,
    @SerialName("suggested_qty") val suggestedQty: List<JsonElement>? = null,
)

@Serializable
data class Sku(
    @SerialName("id") val id: Long,
    @SerialName("code") val code: String,
    @SerialName("variant_id") val variantId: Long,
    @SerialName("category_code") val categoryCode: String,
    @SerialName("name") val name: String,
    @SerialName("short_name") val shortName: String,
    @SerialName("name_bn") val nameBn: String? = null,
    @SerialName("base_unit") val baseUnit: String,
    @SerialName("base_per_pack") val basePerPack: Int,
    @SerialName("entry_unit_default") val entryUnitDefault: String,
    @SerialName("report_unit") val reportUnit: String? = null,
    @SerialName("report_factor") val reportFactor: String,
    @SerialName("sort") val sort: Int,
    @SerialName("status") val status: String,
    @SerialName("thumbnail_media_uuid") val thumbnailMediaUuid: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null,
    @SerialName("version") val version: Int? = null,
)

@Serializable
data class SkuPrice(
    @SerialName("id") val id: Long,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("price_type") val priceType: String,
    @SerialName("amount_mtk") val amountMtk: Long,
    @SerialName("per_base_qty") val perBaseQty: Int,
    @SerialName("valid_from") val validFrom: String,
    @SerialName("valid_to") val validTo: String? = null,
)

/** Credit memo with an open due, so the phone can collect and print the balance offline. */
@Serializable
data class OpenMemo(
    @SerialName("memo_client_uuid") val memoClientUuid: String,
    @SerialName("memo_no") val memoNo: String,
    @SerialName("business_date") val businessDate: String,
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("net_mtk") val netMtk: Long,
    @SerialName("due_mtk") val dueMtk: Long,
)

// ---- Records (docs/24 s4) ----

/** Fields common to every sync record (docs/24 s4.3). Identity never comes from the body; it comes from the token. */
@Serializable
data class RecordEnvelope(
    @SerialName("type") val type: String,
    @SerialName("client_uuid") val clientUuid: String,
    @SerialName("family_uuid") val familyUuid: String,
    @SerialName("rank") val rank: Int,
    @SerialName("schema_version") val schemaVersion: Int,
    @SerialName("business_date") val businessDate: String,
    @SerialName("captured_at") val capturedAt: String,
    @SerialName("captured_elapsed_ms") val capturedElapsedMs: Long,
    @SerialName("boot_count") val bootCount: Int,
    @SerialName("clock_offset_ms") val clockOffsetMs: Long? = null,
    @SerialName("captured_offline") val capturedOffline: Boolean,
    @SerialName("route_id") val routeId: Long? = null,
    @SerialName("acting_for_user_id") val actingForUserId: Long? = null,
    @SerialName("bundle_version") val bundleVersion: String? = null,
    @SerialName("bundle_stale") val bundleStale: Boolean = false,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("sig") val sig: String? = null,
)

/** One on-demand location fix with the integrity evidence captured with it (docs/24 s11.1). */
@Serializable
data class GeoFix(
    @SerialName("purpose") val purpose: String,
    @SerialName("fix_status") val fixStatus: String,
    @SerialName("lat") val lat: Double?,
    @SerialName("lng") val lng: Double?,
    @SerialName("accuracy_m") val accuracyM: Double?,
    @SerialName("altitude_m") val altitudeM: Double? = null,
    @SerialName("vertical_accuracy_m") val verticalAccuracyM: Double? = null,
    @SerialName("speed_mps") val speedMps: Double? = null,
    @SerialName("bearing_deg") val bearingDeg: Double? = null,
    @SerialName("provider") val provider: String,
    @SerialName("fix_time") val fixTime: String? = null,
    @SerialName("fix_elapsed_realtime_ms") val fixElapsedRealtimeMs: Long? = null,
    @SerialName("fix_age_ms") val fixAgeMs: Int? = null,
    @SerialName("time_to_fix_ms") val timeToFixMs: Int? = null,
    @SerialName("request_priority") val requestPriority: String? = null,
    @SerialName("is_mock") val isMock: Boolean,
    @SerialName("reused") val reused: Boolean,
    @SerialName("refresh_count") val refreshCount: Int? = null,
    @SerialName("gnss") val gnss: GnssSummary? = null,
    @SerialName("radio") val radio: JsonObject? = null,
    @SerialName("device") val device: FixDeviceState,
)

/** Device integrity facts read at the moment of the fix. */
@Serializable
data class FixDeviceState(
    @SerialName("device_owner") val deviceOwner: Boolean,
    @SerialName("dev_options_enabled") val devOptionsEnabled: Boolean,
    @SerialName("adb_enabled") val adbEnabled: Boolean,
    @SerialName("auto_time_enabled") val autoTimeEnabled: Boolean,
    @SerialName("mock_app_present") val mockAppPresent: Boolean,
    @SerialName("integrity_ref") val integrityRef: String? = null,
)

/** GnssStatus (and optional GnssMeasurement) statistics collected only while the fix request was open. */
@Serializable
data class GnssSummary(
    @SerialName("window_ms") val windowMs: Int,
    @SerialName("satellites_visible") val satellitesVisible: Int,
    @SerialName("satellites_used") val satellitesUsed: Int,
    @SerialName("constellations_used") val constellationsUsed: List<String>,
    @SerialName("cn0_used_mean_dbhz") val cn0UsedMeanDbhz: Double? = null,
    @SerialName("cn0_used_max_dbhz") val cn0UsedMaxDbhz: Double? = null,
    @SerialName("cn0_used_stddev_dbhz") val cn0UsedStddevDbhz: Double? = null,
    @SerialName("cn0_all_mean_dbhz") val cn0AllMeanDbhz: Double? = null,
    @SerialName("ephemeris_share") val ephemerisShare: Double? = null,
    @SerialName("raw_supported") val rawSupported: Boolean? = null,
    @SerialName("raw_measurement_count") val rawMeasurementCount: Int? = null,
    @SerialName("agc_db_mean") val agcDbMean: Double? = null,
)

/** The phone's geofence decision (docs/24 s11.2); the server re-checks and stores its own verdict beside it. */
@Serializable
data class DeviceGeoVerdict(
    @SerialName("verdict") val verdict: String,
    @SerialName("distance_m") val distanceM: Double? = null,
    @SerialName("radius_m_used") val radiusMUsed: Int,
    @SerialName("max_accuracy_m_used") val maxAccuracyMUsed: Int,
    @SerialName("location_basis") val locationBasis: String,
    @SerialName("outlet_lat") val outletLat: Double? = null,
    @SerialName("outlet_lng") val outletLng: Double? = null,
    @SerialName("action") val action: String,
    @SerialName("force_reason_code") val forceReasonCode: String? = null,
    @SerialName("force_photo_uuid") val forcePhotoUuid: String? = null,
)

@Serializable
data class AttendanceEventPayload(
    @SerialName("kind") val kind: String,
    @SerialName("fix") val fix: GeoFix,
    @SerialName("address_display") val addressDisplay: String? = null,
)

/** One event per SKU per Save (an increment, never an overwrite). qty_entered is negative only for kind adjustment. */
@Serializable
data class StockMovementPayload(
    @SerialName("kind") val kind: String,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("qty_entered") val qtyEntered: Int,
    @SerialName("unit_entered") val unitEntered: String,
    @SerialName("pack_factor") val packFactor: Int,
    @SerialName("qty_base") val qtyBase: Int,
    @SerialName("reason_code") val reasonCode: String? = null,
    @SerialName("slip_printed") val slipPrinted: Boolean,
)

/** Immutable facts at outlet open. The visit is the family root (rank 0, family_uuid = its client_uuid). */
@Serializable
data class VisitPayload(
    @SerialName("visit_kind") val visitKind: String,
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("opened_at") val openedAt: String,
    @SerialName("sequence_no") val sequenceNo: Int,
    @SerialName("planned") val planned: Boolean,
    @SerialName("assessed_user_id") val assessedUserId: Long? = null,
    @SerialName("fix") val fix: GeoFix,
    @SerialName("geo") val geo: DeviceGeoVerdict,
)

@Serializable
data class VisitClosePayload(
    @SerialName("visit_client_uuid") val visitClientUuid: String,
    @SerialName("outcome_code") val outcomeCode: String,
    @SerialName("call_started_at") val callStartedAt: String? = null,
    @SerialName("call_declined") val callDeclined: Boolean,
    @SerialName("ended_at") val endedAt: String,
    @SerialName("is_zero_sale") val isZeroSale: Boolean,
)

/** Memo header committed with its lines, discount lines and QC lines in one phone transaction. Server-checked */
@Serializable
data class MemoPayload(
    @SerialName("visit_client_uuid") val visitClientUuid: String,
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("memo_no") val memoNo: String,
    @SerialName("memo_kind") val memoKind: String,
    @SerialName("committed_at") val committedAt: String,
    @SerialName("price_list_date") val priceListDate: String,
    @SerialName("price_type") val priceType: String,
    @SerialName("gross_mtk") val grossMtk: Long,
    @SerialName("offer_discount_mtk") val offerDiscountMtk: Long,
    @SerialName("drp_discount_mtk") val drpDiscountMtk: Long,
    @SerialName("qc_deduction_mtk") val qcDeductionMtk: Long,
    @SerialName("round_adj_mtk") val roundAdjMtk: Int,
    @SerialName("net_mtk") val netMtk: Long,
    @SerialName("paid_mtk") val paidMtk: Long,
    @SerialName("due_mtk") val dueMtk: Long,
    @SerialName("is_credit") val isCredit: Boolean,
    @SerialName("outstanding_before_mtk") val outstandingBeforeMtk: Long? = null,
    @SerialName("line_count") val lineCount: Int,
    @SerialName("discount_line_count") val discountLineCount: Int,
    @SerialName("qc_line_count") val qcLineCount: Int,
    @SerialName("supersedes_client_uuid") val supersedesClientUuid: String? = null,
    @SerialName("edit_reason_code") val editReasonCode: String? = null,
    @SerialName("edit_fix") val editFix: GeoFix? = null,
    @SerialName("offer_version_ids") val offerVersionIds: List<Long>? = null,
    @SerialName("rounding_mode") val roundingMode: String,
)

/** gross_mtk = div_half_up(qty_base x base_price_mtk, price_per_qty) (reject arithmetic_mismatch otherwise). */
@Serializable
data class MemoLinePayload(
    @SerialName("memo_client_uuid") val memoClientUuid: String,
    @SerialName("line_no") val lineNo: Int,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("line_kind") val lineKind: String,
    @SerialName("qty_entered") val qtyEntered: Int,
    @SerialName("unit_entered") val unitEntered: String,
    @SerialName("pack_factor") val packFactor: Int,
    @SerialName("qty_base") val qtyBase: Int,
    @SerialName("price_type") val priceType: String,
    @SerialName("price_valid_from") val priceValidFrom: String,
    @SerialName("base_price_mtk") val basePriceMtk: Long,
    @SerialName("price_per_qty") val pricePerQty: Int,
    @SerialName("gross_mtk") val grossMtk: Long,
    @SerialName("offer_id") val offerId: Long? = null,
)

/** One discount component as (sku, qty, value, kind) so every reading of the memo's Discount table fits (Q-UI-01). */
@Serializable
data class MemoDiscountPayload(
    @SerialName("memo_client_uuid") val memoClientUuid: String,
    @SerialName("kind") val kind: String,
    @SerialName("sku_id") val skuId: Long? = null,
    @SerialName("qty_base") val qtyBase: Int? = null,
    @SerialName("value_mtk") val valueMtk: Long,
    @SerialName("offer_id") val offerId: Long? = null,
    @SerialName("offer_version_id") val offerVersionId: Long? = null,
    @SerialName("basis_qty_base") val basisQtyBase: Int? = null,
    @SerialName("line_no") val lineNo: Int? = null,
)

@Serializable
data class QcLinePayload(
    @SerialName("visit_client_uuid") val visitClientUuid: String,
    @SerialName("memo_client_uuid") val memoClientUuid: String? = null,
    @SerialName("applied_to_memo") val appliedToMemo: Boolean,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("fault_type_code") val faultTypeCode: String,
    @SerialName("fault_group") val faultGroup: String,
    @SerialName("qty_base") val qtyBase: Int,
    @SerialName("unit_price_mtk") val unitPriceMtk: Long,
    @SerialName("settlement_mtk") val settlementMtk: Long,
)

// ---- Sync batch ----

@Serializable
data class SyncBatchRequest(
    @SerialName("batch_uuid") val batchUuid: String,
    @SerialName("device_uuid") val deviceUuid: String,
    @SerialName("schema_version") val schemaVersion: Int,
    @SerialName("app_version") val appVersion: String,
    @SerialName("trigger") val trigger: String,
    @SerialName("sent_at_device") val sentAtDevice: String,
    @SerialName("pending_rows") val pendingRows: Int,
    @SerialName("time_anchors") val timeAnchors: List<JsonElement>,
    @SerialName("device_counts") val deviceCounts: Map<String, JsonElement>,
    @SerialName("device_money") val deviceMoney: Map<String, JsonElement>? = null,
    @SerialName("telemetry") val telemetry: JsonElement? = null,
    @SerialName("records") val records: List<JsonObject>,
)

@Serializable
data class SyncBatchSummary(
    @SerialName("accepted") val accepted: Int,
    @SerialName("duplicate") val duplicate: Int,
    @SerialName("rejected") val rejected: Int,
    @SerialName("quarantined") val quarantined: Int,
)

@Serializable
data class SyncBatchResponse(
    @SerialName("batch_uuid") val batchUuid: String,
    @SerialName("replayed") val replayed: Boolean,
    @SerialName("received_at") val receivedAt: String,
    @SerialName("acks") val acks: List<RecordAck>,
    @SerialName("summary") val summary: SyncBatchSummary,
    @SerialName("server_totals") val serverTotals: List<JsonElement>,
    @SerialName("day_states") val dayStates: List<JsonElement>,
    @SerialName("supervisor_day") val supervisorDay: JsonElement? = null,
    @SerialName("resolutions") val resolutions: List<JsonElement>,
    @SerialName("hold_s") val holdS: Int,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("bundle_version_current") val bundleVersionCurrent: String? = null,
    @SerialName("generation") val generation: String,
    @SerialName("directives") val directives: List<JsonElement>? = null,
)

@Serializable
data class RecordAck(
    @SerialName("client_uuid") val clientUuid: String,
    @SerialName("type") val type: String,
    @SerialName("status") val status: String,
    @SerialName("code") val code: String? = null,
    @SerialName("retryable") val retryable: Boolean? = null,
    @SerialName("message_key") val messageKey: String? = null,
    @SerialName("server_id") val serverId: Long? = null,
)
