// GENERATED by shared/contract/tools/gen_wire_dtos.py from contract/slices/schemas (source of truth: contract/openapi.yaml).
// Do not edit by hand: change the contract, regenerate the slices (tools/slice-contract.py) and re-run the generator.
// WireDtosDriftTest compares every member here with the slice fields (name, required, nullable, JSON type).
package com.aktcl.aron.contract

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonTransformingSerializer
import kotlinx.serialization.json.JsonObject

// ---- Auth (docs/24 s5) ----

@Serializable
data class LoginRequest(
    @SerialName("username") val username: String,
    @SerialName("password") val password: String,
    @SerialName("client") val client: String,
    @SerialName("device_uuid") val deviceUuid: String? = null,
) {
    override fun toString(): String = "LoginRequest(username=${username}, password=***, client=${client}, deviceUuid=${deviceUuid})"
}

/** For `client: web` with `status: password_change_required`, `access_token` is null and `password_change_token` carries a short-lived (10 min) token accepted only by `POST /v1/auth/change-password` (Authorization: Bearer). TOTP, when the role requires it, comes after the password change: the change-password success response then continues to the `mfa_required` step as for a normal login (docs/24 s14a R15). */
@Serializable
data class LoginResponse(
    @SerialName("status") val status: String,
    @SerialName("access_token") val accessToken: String? = null,
    @SerialName("access_expires_at") val accessExpiresAt: String? = null,
    @SerialName("refresh_token") val refreshToken: String? = null,
    @SerialName("refresh_expires_at") val refreshExpiresAt: String? = null,
    @SerialName("upload_refresh_token") val uploadRefreshToken: String? = null,
    @SerialName("bind_token") val bindToken: String? = null,
    @SerialName("mfa_token") val mfaToken: String? = null,
    @SerialName("password_change_token") val passwordChangeToken: String? = null,
    @SerialName("user") val user: UserSummary,
    @SerialName("scope") val scope: ScopeSummary? = null,
    @Serializable(with = LoginDeviceWire::class) @SerialName("device") val device: LoginDevice? = null,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("server_time") val serverTime: String,
    @SerialName("min_app_version_code") val minAppVersionCode: Int? = null,
) {
    override fun toString(): String = "LoginResponse(status=${status}, accessToken=***, accessExpiresAt=${accessExpiresAt}, refreshToken=***, refreshExpiresAt=${refreshExpiresAt}, uploadRefreshToken=***, bindToken=***, mfaToken=***, passwordChangeToken=***, user=${user}, scope=${scope}, device=${device}, configVersion=${configVersion}, serverTime=${serverTime}, minAppVersionCode=${minAppVersionCode})"
}

@Serializable
data class UserSummary(
    @SerialName("user_id") val userId: Long,
    @SerialName("username") val username: String,
    @SerialName("full_name") val fullName: String,
    @SerialName("role") val role: String,
    @SerialName("designation") val designation: String? = null,
    @SerialName("locale") val locale: String,
)

@Serializable
data class ScopeSummary(
    @SerialName("scope_version") val scopeVersion: Int,
    @SerialName("nodes") val nodes: List<NodeRef>,
)

@Serializable
data class NodeRef(
    @SerialName("type") val type: String,
    @SerialName("id") val id: Long,
    @SerialName("code") val code: String? = null,
    @SerialName("name") val name: String? = null,
) {
    override fun toString(): String = "NodeRef(type=${type}, id=${id}, code=***, name=${name})"
}

@Serializable
data class LoginDevice(
    @SerialName("device_id") val deviceId: Long,
    @SerialName("bind_ordinal") val bindOrdinal: Int?,
    @SerialName("memo_seq_block_size") val memoSeqBlockSize: Int,
)

/** Encode LoginDevice with this serializer (nested fields already do): required-nullable members stay on the wire as explicit null (R7) even when the Json omits nulls. */
object LoginDeviceWire : JsonTransformingSerializer<LoginDevice>(LoginDevice.serializer()) {
    private val alwaysEmitted = listOf("bind_ordinal")
    override fun transformSerialize(element: JsonElement): JsonElement =
        if (element is JsonObject) JsonObject(element + alwaysEmitted.filter { it !in element }.associateWith { JsonNull }) else element
}

@Serializable
data class RefreshRequest(
    @SerialName("refresh_token") val refreshToken: String? = null,
    @SerialName("grant") val grant: String,
    @SerialName("device_uuid") val deviceUuid: String? = null,
) {
    override fun toString(): String = "RefreshRequest(refreshToken=***, grant=${grant}, deviceUuid=${deviceUuid})"
}

@Serializable
data class TokenPair(
    @SerialName("access_token") val accessToken: String,
    @SerialName("access_expires_at") val accessExpiresAt: String,
    @SerialName("refresh_token") val refreshToken: String? = null,
    @SerialName("refresh_expires_at") val refreshExpiresAt: String,
    @SerialName("scope_version") val scopeVersion: Int,
    @SerialName("server_time") val serverTime: String,
) {
    override fun toString(): String = "TokenPair(accessToken=***, accessExpiresAt=${accessExpiresAt}, refreshToken=***, refreshExpiresAt=${refreshExpiresAt}, scopeVersion=${scopeVersion}, serverTime=${serverTime})"
}

@Serializable
data class LogoutRequest(
    @SerialName("scope") val scope: String,
    @SerialName("refresh_token") val refreshToken: String? = null,
) {
    override fun toString(): String = "LogoutRequest(scope=${scope}, refreshToken=***)"
}

// ---- Bundle (docs/24 s3.6) ----

@Serializable
data class PagedSection(
    @SerialName("section") val section: String,
    @SerialName("pages") val pages: Int,
    @SerialName("rows") val rows: Int,
)

@Serializable
data class BundleMeta(
    @SerialName("bundle_version") val bundleVersion: String,
    @SerialName("valid_for_business_date") val validForBusinessDate: String,
    @SerialName("generated_at") val generatedAt: String,
    @SerialName("server_time") val serverTime: String,
    @SerialName("user_id") val userId: Long,
    @SerialName("role") val role: String,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("schema_version") val schemaVersion: Int,
    @SerialName("cursor") val cursor: String,
    @SerialName("is_prefetch") val isPrefetch: Boolean? = null,
    @SerialName("paged_sections") val pagedSections: List<PagedSection>,
)

@Serializable
data class BundleUser(
    @SerialName("user_id") val userId: Long,
    @SerialName("username") val username: String,
    @SerialName("full_name") val fullName: String,
    @SerialName("role") val role: String,
    @SerialName("designation") val designation: String? = null,
    @SerialName("locale") val locale: String,
    @SerialName("bind_ordinal") val bindOrdinal: Int,
    @SerialName("memo_seq_block_size") val memoSeqBlockSize: Int,
    @SerialName("zone_id") val zoneId: Long? = null,
    @SerialName("territory_id") val territoryId: Long? = null,
)

@Serializable
data class RouteAssignees(
    @SerialName("user_id") val userId: Long,
    @SerialName("full_name") val fullName: String,
    @SerialName("role") val role: String,
    @SerialName("username") val username: String,
)

@Serializable
data class Route(
    @SerialName("created_at") val createdAt: String,
    @SerialName("updated_at") val updatedAt: String,
    @SerialName("version") val version: Int,
    @SerialName("id") val id: Long,
    @SerialName("code") val code: String,
    @SerialName("name") val name: String,
    @SerialName("display_label") val displayLabel: String? = null,
    @SerialName("zone_id") val zoneId: Long,
    @SerialName("kind") val kind: String,
    @SerialName("visit_kind") val visitKind: String? = null,
    @SerialName("visit_days_mask") val visitDaysMask: Int,
    @SerialName("sequence_no") val sequenceNo: Int? = null,
    @SerialName("status") val status: String,
    @SerialName("assignees") val assignees: List<RouteAssignees>? = null,
) {
    override fun toString(): String = "Route(createdAt=${createdAt}, updatedAt=${updatedAt}, version=${version}, id=${id}, code=***, name=${name}, displayLabel=${displayLabel}, zoneId=${zoneId}, kind=${kind}, visitKind=${visitKind}, visitDaysMask=${visitDaysMask}, sequenceNo=${sequenceNo}, status=${status}, assignees=${assignees})"
}

/** Per-route section of the bundle; replaced as a whole when the route is added to the user. */
@Serializable
data class RouteSnapshot(
    @SerialName("route_id") val routeId: Long,
    @SerialName("route_snapshot_version") val routeSnapshotVersion: Int,
    @SerialName("route") val route: Route,
    @SerialName("assignment_kind") val assignmentKind: String,
    @SerialName("acting_for_user_id") val actingForUserId: Long? = null,
    @SerialName("planned_today") val plannedToday: Boolean,
    @SerialName("target_outlets") val targetOutlets: Int,
    @SerialName("outlets") val outlets: List<BundleOutlet>,
    @SerialName("open_memos") val openMemos: List<OpenMemo>,
    @SerialName("sales_plan_sku_ids") val salesPlanSkuIds: List<Long>,
    @SerialName("targets") val targets: List<JsonElement>,
    @SerialName("achievement_mtd") val achievementMtd: List<JsonElement>,
    @SerialName("day_state") val dayState: RouteDayState,
)

/** Outlet as the phone needs it. `radius_m` and `max_accuracy_m` are already resolved for this outlet (outlet > route > zone > geo_class > territory > division > wing > global). */
@Serializable
data class BundleOutlet(
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("route_id") val routeId: Long,
    @SerialName("code") val code: String,
    @SerialName("name") val name: String,
    @SerialName("name_bn") val nameBn: String? = null,
    @SerialName("name_sort_key") val nameSortKey: String,
    @SerialName("owner_name") val ownerName: String,
    @SerialName("contact_number") val contactNumber: String? = null,
    @SerialName("lat") val lat: Double? = null,
    @SerialName("lng") val lng: Double? = null,
    @SerialName("location_confirmed") val locationConfirmed: Boolean,
    @SerialName("provisional_lat") val provisionalLat: Double? = null,
    @SerialName("provisional_lng") val provisionalLng: Double? = null,
    @SerialName("cluster_id") val clusterId: Long,
    @SerialName("cluster_name") val clusterName: String,
    @SerialName("channel") val channel: String,
    @SerialName("sub_channel_id") val subChannelId: Long? = null,
    @SerialName("geo_class") val geoClass: String? = null,
    @SerialName("status") val status: String,
    @SerialName("price_type") val priceType: String,
    @SerialName("outlet_kind") val outletKind: String,
    @SerialName("radius_m") val radiusM: Int,
    @SerialName("max_accuracy_m") val maxAccuracyM: Int,
    @SerialName("visit_sequence") val visitSequence: Int? = null,
    @SerialName("open_due_mtk") val openDueMtk: Long,
    @SerialName("open_due_as_of") val openDueAsOf: String? = null,
    @SerialName("programme_flags") val programmeFlags: List<String>,
    @SerialName("pending_request") val pendingRequest: Boolean,
    @SerialName("suggested_qty") val suggestedQty: List<JsonElement>? = null,
) {
    override fun toString(): String = "BundleOutlet(outletId=${outletId}, routeId=${routeId}, code=***, name=${name}, nameBn=${nameBn}, nameSortKey=${nameSortKey}, ownerName=${ownerName}, contactNumber=${contactNumber}, lat=${lat}, lng=${lng}, locationConfirmed=${locationConfirmed}, provisionalLat=${provisionalLat}, provisionalLng=${provisionalLng}, clusterId=${clusterId}, clusterName=${clusterName}, channel=${channel}, subChannelId=${subChannelId}, geoClass=${geoClass}, status=${status}, priceType=${priceType}, outletKind=${outletKind}, radiusM=${radiusM}, maxAccuracyM=${maxAccuracyM}, visitSequence=${visitSequence}, openDueMtk=${openDueMtk}, openDueAsOf=${openDueAsOf}, programmeFlags=${programmeFlags}, pendingRequest=${pendingRequest}, suggestedQty=${suggestedQty})"
}

@Serializable
data class Sku(
    @SerialName("id") val id: Long,
    @SerialName("code") val code: String,
    @SerialName("variant_id") val variantId: Long,
    @SerialName("category_code") val categoryCode: String,
    @SerialName("name") val name: String,
    @SerialName("short_name") val shortName: String,
    @SerialName("name_bn") val nameBn: String? = null,
    @SerialName("base_unit") val baseUnit: String,
    @SerialName("base_per_pack") val basePerPack: Int,
    @SerialName("entry_unit_default") val entryUnitDefault: String,
    @SerialName("report_unit") val reportUnit: String? = null,
    @SerialName("report_factor") val reportFactor: String,
    @SerialName("sort") val sort: Int,
    @SerialName("status") val status: String,
    @SerialName("thumbnail_media_uuid") val thumbnailMediaUuid: String? = null,
    @SerialName("updated_at") val updatedAt: String? = null,
    @SerialName("version") val version: Int? = null,
) {
    override fun toString(): String = "Sku(id=${id}, code=***, variantId=${variantId}, categoryCode=${categoryCode}, name=${name}, shortName=${shortName}, nameBn=${nameBn}, baseUnit=${baseUnit}, basePerPack=${basePerPack}, entryUnitDefault=${entryUnitDefault}, reportUnit=${reportUnit}, reportFactor=${reportFactor}, sort=${sort}, status=${status}, thumbnailMediaUuid=${thumbnailMediaUuid}, updatedAt=${updatedAt}, version=${version})"
}

@Serializable
data class SkuPrice(
    @SerialName("id") val id: Long,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("price_type") val priceType: String,
    @SerialName("amount_mtk") val amountMtk: Long,
    @SerialName("per_base_qty") val perBaseQty: Int,
    @SerialName("valid_from") val validFrom: String,
    @SerialName("valid_to") val validTo: String? = null,
)

/** Credit memo with an open due, so the phone can collect and print the balance offline. */
@Serializable
data class OpenMemo(
    @SerialName("memo_client_uuid") val memoClientUuid: String,
    @SerialName("memo_no") val memoNo: String,
    @SerialName("business_date") val businessDate: String,
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("net_mtk") val netMtk: Long,
    @SerialName("due_mtk") val dueMtk: Long,
)

// ---- Records (docs/24 s4) ----

/** Fields common to every sync record (docs/24 s4.3). Identity never comes from the body; it comes from the token. */
@Serializable
data class RecordEnvelope(
    @SerialName("type") val type: String,
    @SerialName("client_uuid") val clientUuid: String,
    @SerialName("family_uuid") val familyUuid: String,
    @SerialName("rank") val rank: Int,
    @SerialName("schema_version") val schemaVersion: Int,
    @SerialName("business_date") val businessDate: String,
    @SerialName("captured_at") val capturedAt: String,
    @SerialName("captured_elapsed_ms") val capturedElapsedMs: Long,
    @SerialName("boot_count") val bootCount: Int,
    @SerialName("clock_offset_ms") val clockOffsetMs: Long? = null,
    @SerialName("captured_offline") val capturedOffline: Boolean,
    @SerialName("route_id") val routeId: Long? = null,
    @SerialName("acting_for_user_id") val actingForUserId: Long? = null,
    @SerialName("bundle_version") val bundleVersion: String? = null,
    @SerialName("bundle_stale") val bundleStale: Boolean = false,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("sig") val sig: String? = null,
)

/** Required members lat, lng, accuracy_m may be null: encode records with explicitNulls = true so a no-fix GeoFix keeps its keys. One on-demand location fix with the integrity evidence captured with it (docs/24 s11.1). */
@Serializable
data class GeoFix(
    @SerialName("purpose") val purpose: String,
    @SerialName("fix_status") val fixStatus: String,
    @SerialName("lat") val lat: Double?,
    @SerialName("lng") val lng: Double?,
    @SerialName("accuracy_m") val accuracyM: Double?,
    @SerialName("altitude_m") val altitudeM: Double? = null,
    @SerialName("vertical_accuracy_m") val verticalAccuracyM: Double? = null,
    @SerialName("speed_mps") val speedMps: Double? = null,
    @SerialName("bearing_deg") val bearingDeg: Double? = null,
    @SerialName("provider") val provider: String,
    @SerialName("fix_time") val fixTime: String? = null,
    @SerialName("fix_elapsed_realtime_ms") val fixElapsedRealtimeMs: Long? = null,
    @SerialName("fix_age_ms") val fixAgeMs: Int? = null,
    @SerialName("time_to_fix_ms") val timeToFixMs: Int? = null,
    @SerialName("request_priority") val requestPriority: String? = null,
    @SerialName("is_mock") val isMock: Boolean,
    @SerialName("reused") val reused: Boolean,
    @SerialName("refresh_count") val refreshCount: Int? = null,
    @SerialName("gnss") val gnss: GnssSummary? = null,
    @SerialName("radio") val radio: JsonObject? = null,
    @SerialName("device") val device: FixDeviceState,
)

/** Encode GeoFix with this serializer (nested fields already do): required-nullable members stay on the wire as explicit null (R7) even when the Json omits nulls. */
object GeoFixWire : JsonTransformingSerializer<GeoFix>(GeoFix.serializer()) {
    private val alwaysEmitted = listOf("lat", "lng", "accuracy_m")
    override fun transformSerialize(element: JsonElement): JsonElement =
        if (element is JsonObject) JsonObject(element + alwaysEmitted.filter { it !in element }.associateWith { JsonNull }) else element
}

/** Device integrity facts read at the moment of the fix. */
@Serializable
data class FixDeviceState(
    @SerialName("device_owner") val deviceOwner: Boolean,
    @SerialName("dev_options_enabled") val devOptionsEnabled: Boolean,
    @SerialName("adb_enabled") val adbEnabled: Boolean,
    @SerialName("auto_time_enabled") val autoTimeEnabled: Boolean,
    @SerialName("mock_app_present") val mockAppPresent: Boolean,
    @SerialName("integrity_ref") val integrityRef: String? = null,
)

/** GnssStatus (and optional GnssMeasurement) statistics collected only while the fix request was open. */
@Serializable
data class GnssSummary(
    @SerialName("window_ms") val windowMs: Int,
    @SerialName("satellites_visible") val satellitesVisible: Int,
    @SerialName("satellites_used") val satellitesUsed: Int,
    @SerialName("constellations_used") val constellationsUsed: List<String>,
    @SerialName("cn0_used_mean_dbhz") val cn0UsedMeanDbhz: Double? = null,
    @SerialName("cn0_used_max_dbhz") val cn0UsedMaxDbhz: Double? = null,
    @SerialName("cn0_used_stddev_dbhz") val cn0UsedStddevDbhz: Double? = null,
    @SerialName("cn0_all_mean_dbhz") val cn0AllMeanDbhz: Double? = null,
    @SerialName("ephemeris_share") val ephemerisShare: Double? = null,
    @SerialName("raw_supported") val rawSupported: Boolean? = null,
    @SerialName("raw_measurement_count") val rawMeasurementCount: Int? = null,
    @SerialName("agc_db_mean") val agcDbMean: Double? = null,
)

/** The phone's geofence decision (docs/24 s11.2); the server re-checks and stores its own verdict beside it. */
@Serializable
data class DeviceGeoVerdict(
    @SerialName("verdict") val verdict: String,
    @SerialName("distance_m") val distanceM: Double? = null,
    @SerialName("radius_m_used") val radiusMUsed: Int,
    @SerialName("max_accuracy_m_used") val maxAccuracyMUsed: Int,
    @SerialName("location_basis") val locationBasis: String,
    @SerialName("outlet_lat") val outletLat: Double? = null,
    @SerialName("outlet_lng") val outletLng: Double? = null,
    @SerialName("action") val action: String,
    @SerialName("force_reason_code") val forceReasonCode: String? = null,
    @SerialName("force_photo_uuid") val forcePhotoUuid: String? = null,
)

@Serializable
data class AttendanceEventPayload(
    @SerialName("kind") val kind: String,
    @Serializable(with = GeoFixWire::class) @SerialName("fix") val fix: GeoFix,
    @SerialName("address_display") val addressDisplay: String? = null,
)

/** One event per SKU per Save (an increment, never an overwrite). qty_entered is negative only for kind adjustment. */
@Serializable
data class StockMovementPayload(
    @SerialName("kind") val kind: String,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("qty_entered") val qtyEntered: Int,
    @SerialName("unit_entered") val unitEntered: String,
    @SerialName("pack_factor") val packFactor: Int,
    @SerialName("qty_base") val qtyBase: Int,
    @SerialName("reason_code") val reasonCode: String? = null,
    @SerialName("slip_printed") val slipPrinted: Boolean,
)

/** Immutable facts at outlet open. The visit is the family root (rank 0, family_uuid = its client_uuid). */
@Serializable
data class VisitPayload(
    @SerialName("visit_kind") val visitKind: String,
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("opened_at") val openedAt: String,
    @SerialName("sequence_no") val sequenceNo: Int,
    @SerialName("planned") val planned: Boolean,
    @SerialName("assessed_user_id") val assessedUserId: Long? = null,
    @Serializable(with = GeoFixWire::class) @SerialName("fix") val fix: GeoFix,
    @SerialName("geo") val geo: DeviceGeoVerdict,
)

@Serializable
data class VisitClosePayload(
    @SerialName("visit_client_uuid") val visitClientUuid: String,
    @SerialName("outcome_code") val outcomeCode: String,
    @SerialName("call_started_at") val callStartedAt: String? = null,
    @SerialName("call_declined") val callDeclined: Boolean,
    @SerialName("ended_at") val endedAt: String,
    @SerialName("is_zero_sale") val isZeroSale: Boolean,
)

/** Memo header committed with its lines, discount lines and QC lines in one phone transaction. Server-checked */
@Serializable
data class MemoPayload(
    @SerialName("visit_client_uuid") val visitClientUuid: String,
    @SerialName("outlet_id") val outletId: Long,
    @SerialName("memo_no") val memoNo: String,
    @SerialName("memo_kind") val memoKind: String,
    @SerialName("committed_at") val committedAt: String,
    @SerialName("price_list_date") val priceListDate: String,
    @SerialName("price_type") val priceType: String,
    @SerialName("gross_mtk") val grossMtk: Long,
    @SerialName("offer_discount_mtk") val offerDiscountMtk: Long,
    @SerialName("drp_discount_mtk") val drpDiscountMtk: Long,
    @SerialName("qc_deduction_mtk") val qcDeductionMtk: Long,
    @SerialName("round_adj_mtk") val roundAdjMtk: Int,
    @SerialName("net_mtk") val netMtk: Long,
    @SerialName("paid_mtk") val paidMtk: Long,
    @SerialName("due_mtk") val dueMtk: Long,
    @SerialName("is_credit") val isCredit: Boolean,
    @SerialName("outstanding_before_mtk") val outstandingBeforeMtk: Long? = null,
    @SerialName("line_count") val lineCount: Int,
    @SerialName("discount_line_count") val discountLineCount: Int,
    @SerialName("qc_line_count") val qcLineCount: Int,
    @SerialName("supersedes_client_uuid") val supersedesClientUuid: String? = null,
    @SerialName("edit_reason_code") val editReasonCode: String? = null,
    @Serializable(with = GeoFixWire::class) @SerialName("edit_fix") val editFix: GeoFix? = null,
    @SerialName("offer_version_ids") val offerVersionIds: List<Long>? = null,
    @SerialName("rounding_mode") val roundingMode: String,
)

/** gross_mtk = div_half_up(qty_base x base_price_mtk, price_per_qty) (reject arithmetic_mismatch otherwise). */
@Serializable
data class MemoLinePayload(
    @SerialName("memo_client_uuid") val memoClientUuid: String,
    @SerialName("line_no") val lineNo: Int,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("line_kind") val lineKind: String,
    @SerialName("qty_entered") val qtyEntered: Int,
    @SerialName("unit_entered") val unitEntered: String,
    @SerialName("pack_factor") val packFactor: Int,
    @SerialName("qty_base") val qtyBase: Int,
    @SerialName("price_type") val priceType: String,
    @SerialName("price_valid_from") val priceValidFrom: String,
    @SerialName("base_price_mtk") val basePriceMtk: Long,
    @SerialName("price_per_qty") val pricePerQty: Int,
    @SerialName("gross_mtk") val grossMtk: Long,
    @SerialName("offer_id") val offerId: Long? = null,
)

/** One discount component as (sku, qty, value, kind) so every reading of the memo's Discount table fits (Q-UI-01). */
@Serializable
data class MemoDiscountPayload(
    @SerialName("memo_client_uuid") val memoClientUuid: String,
    @SerialName("kind") val kind: String,
    @SerialName("sku_id") val skuId: Long? = null,
    @SerialName("qty_base") val qtyBase: Int? = null,
    @SerialName("value_mtk") val valueMtk: Long,
    @SerialName("offer_id") val offerId: Long? = null,
    @SerialName("offer_version_id") val offerVersionId: Long? = null,
    @SerialName("basis_qty_base") val basisQtyBase: Int? = null,
    @SerialName("line_no") val lineNo: Int? = null,
)

@Serializable
data class QcLinePayload(
    @SerialName("visit_client_uuid") val visitClientUuid: String,
    @SerialName("memo_client_uuid") val memoClientUuid: String? = null,
    @SerialName("applied_to_memo") val appliedToMemo: Boolean,
    @SerialName("sku_id") val skuId: Long,
    @SerialName("fault_type_code") val faultTypeCode: String,
    @SerialName("fault_group") val faultGroup: String,
    @SerialName("qty_base") val qtyBase: Int,
    @SerialName("unit_price_mtk") val unitPriceMtk: Long,
    @SerialName("settlement_mtk") val settlementMtk: Long,
)

// ---- Device enrolment, admin identity (contract v1.2) ----

/** Explicit "Play Integrity unavailable" marker sent instead of a token when the phone tried and could not get one. */
@Serializable
data class PlayIntegrityUnavailable(
    @SerialName("reason") val reason: String,
    @SerialName("detail") val detail: String? = null,
)

@Serializable
data class ChangePasswordRequest(
    @SerialName("current_password") val currentPassword: String,
    @SerialName("new_password") val newPassword: String,
) {
    override fun toString(): String = "ChangePasswordRequest(currentPassword=***, newPassword=***)"
}

@Serializable
data class DeviceStatusReportPolicyApplyErrors(
    @SerialName("item") val item: String,
    @SerialName("error") val error: String,
)

@Serializable
data class DeviceStatusReportPrinter(
    @SerialName("bonded_name") val bondedName: String? = null,
    @SerialName("mac_sha256") val macSha256: String? = null,
)

/** Phone status (docs/24 s10.3). Sent by POST /v1/devices/me/status and as the `device_status` record payload. */
@Serializable
data class DeviceStatusReport(
    @SerialName("reported_at") val reportedAt: String,
    @SerialName("trigger") val trigger: String? = null,
    @SerialName("app_version") val appVersion: String,
    @SerialName("device_info") val deviceInfo: DeviceInfo,
    @SerialName("device_owner") val deviceOwner: Boolean,
    @SerialName("lockdown_level_applied") val lockdownLevelApplied: String,
    @SerialName("policy_version_applied") val policyVersionApplied: Long?,
    @SerialName("policy_apply_errors") val policyApplyErrors: List<DeviceStatusReportPolicyApplyErrors>? = null,
    @SerialName("restrictions_applied") val restrictionsApplied: Map<String, Boolean>? = null,
    @SerialName("blocking_active") val blockingActive: Boolean,
    @SerialName("blocking_since") val blockingSince: String? = null,
    @SerialName("suspended_packages") val suspendedPackages: List<String>? = null,
    @SerialName("permissions") val permissions: Map<String, String>? = null,
    @SerialName("battery_optimisation_ignored") val batteryOptimisationIgnored: Boolean? = null,
    @SerialName("user_control_disabled") val userControlDisabled: Boolean? = null,
    @SerialName("location_enabled") val locationEnabled: Boolean,
    @SerialName("location_mode") val locationMode: String? = null,
    @SerialName("dev_options_enabled") val devOptionsEnabled: Boolean,
    @SerialName("adb_enabled") val adbEnabled: Boolean,
    @SerialName("auto_time_enabled") val autoTimeEnabled: Boolean,
    @SerialName("time_zone") val timeZone: String? = null,
    @SerialName("mock_location_apps") val mockLocationApps: List<String>,
    @SerialName("play_services_version") val playServicesVersion: Int? = null,
    @SerialName("play_integrity") val playIntegrity: JsonElement? = null,
    @SerialName("play_integrity_unavailable") val playIntegrityUnavailable: PlayIntegrityUnavailable? = null,
    @SerialName("root_hints") val rootHints: List<String>? = null,
    @SerialName("pending_rows") val pendingRows: Int,
    @SerialName("pending_media") val pendingMedia: Int? = null,
    @SerialName("last_sync_at") val lastSyncAt: String? = null,
    @SerialName("battery_pct") val batteryPct: Int,
    @SerialName("charging") val charging: Boolean? = null,
    @SerialName("free_storage_mb") val freeStorageMb: Int? = null,
    @SerialName("printer") val printer: DeviceStatusReportPrinter? = null,
)

/** Encode DeviceStatusReport with this serializer (nested fields already do): required-nullable members stay on the wire as explicit null (R7) even when the Json omits nulls. */
object DeviceStatusReportWire : JsonTransformingSerializer<DeviceStatusReport>(DeviceStatusReport.serializer()) {
    private val alwaysEmitted = listOf("policy_version_applied")
    override fun transformSerialize(element: JsonElement): JsonElement =
        if (element is JsonObject) JsonObject(element + alwaysEmitted.filter { it !in element }.associateWith { JsonNull }) else element
}

@Serializable
data class EnrolDeviceRequest(
    @SerialName("enrolment_token") val enrolmentToken: String,
    @SerialName("device_uuid") val deviceUuid: String,
    @SerialName("app_package") val appPackage: String,
    @SerialName("app_version") val appVersion: String,
    @SerialName("app_signing_cert_sha256") val appSigningCertSha256: String,
    @SerialName("device_owner") val deviceOwner: Boolean,
    @SerialName("public_key") val publicKey: JwkEcPublicDevice,
    @SerialName("key_attestation_chain") val keyAttestationChain: List<String>,
    @SerialName("device_info") val deviceInfo: DeviceInfo,
    @Serializable(with = DeviceStatusReportWire::class) @SerialName("status") val status: DeviceStatusReport? = null,
    @SerialName("play_integrity_unavailable") val playIntegrityUnavailable: PlayIntegrityUnavailable? = null,
) {
    override fun toString(): String = "EnrolDeviceRequest(enrolmentToken=***, deviceUuid=${deviceUuid}, appPackage=${appPackage}, appVersion=${appVersion}, appSigningCertSha256=${appSigningCertSha256}, deviceOwner=${deviceOwner}, publicKey=${publicKey}, keyAttestationChain=***, deviceInfo=${deviceInfo}, status=${status}, playIntegrityUnavailable=${playIntegrityUnavailable})"
}

@Serializable
data class Me(
    @SerialName("user") val user: UserSummary,
    @SerialName("permissions") val permissions: List<String>,
    @SerialName("scope") val scope: ScopeSummary,
    @SerialName("pii") val pii: Boolean? = null,
    @SerialName("mfa_enabled") val mfaEnabled: Boolean? = null,
    @SerialName("menus") val menus: List<JsonElement>? = null,
)

@Serializable
data class DeviceOtp(
    @SerialName("user_id") val userId: Long,
    @SerialName("username") val username: String,
    @SerialName("full_name") val fullName: String,
    @SerialName("zone_id") val zoneId: Long? = null,
    @SerialName("otp") val otp: String? = null,
    @SerialName("device_model") val deviceModel: String? = null,
    @SerialName("created_at") val createdAt: String,
    @SerialName("expires_at") val expiresAt: String,
    @SerialName("attempts") val attempts: Int,
    @SerialName("employee_code") val employeeCode: String? = null,
    @SerialName("zone_code") val zoneCode: String? = null,
    @SerialName("zone_name") val zoneName: String? = null,
) {
    override fun toString(): String = "DeviceOtp(userId=${userId}, username=${username}, fullName=${fullName}, zoneId=${zoneId}, otp=***, deviceModel=${deviceModel}, createdAt=${createdAt}, expiresAt=${expiresAt}, attempts=${attempts}, employeeCode=${employeeCode}, zoneCode=${zoneCode}, zoneName=${zoneName})"
}

// ---- Device policy and enrolment (docs/24 s10) ----

/** Device public key (Android Keystore, EC P-256). */
@Serializable
data class JwkEcPublicDevice(
    @SerialName("kty") val kty: String,
    @SerialName("crv") val crv: String,
    @SerialName("x") val x: String,
    @SerialName("y") val y: String,
)

@Serializable
data class DeviceInfo(
    @SerialName("manufacturer") val manufacturer: String,
    @SerialName("model") val model: String,
    @SerialName("os_api_level") val osApiLevel: Int,
    @SerialName("os_version") val osVersion: String,
    @SerialName("security_patch") val securityPatch: String? = null,
    @SerialName("abi") val abi: String,
    @SerialName("ram_mb") val ramMb: Int,
    @SerialName("storage_total_mb") val storageTotalMb: Int? = null,
)

@Serializable
data class PermissionGrant(
    @SerialName("permission") val permission: String,
    @SerialName("state") val state: String,
    @SerialName("min_api") val minApi: Int,
)

@Serializable
data class AppControlPolicy(
    @SerialName("mode") val mode: String,
    @SerialName("blocked_packages") val blockedPackages: List<String>,
    @SerialName("allowed_packages") val allowedPackages: List<String>,
    @SerialName("always_allowed_packages") val alwaysAllowedPackages: List<String>,
)

/** App blocking tied to attendance (evaluated on the phone on trusted time, offline). */
@Serializable
data class BlockingSchedule(
    @SerialName("enabled") val enabled: Boolean,
    @SerialName("starts_on") val startsOn: String,
    @SerialName("ends_on") val endsOn: String,
    @SerialName("hard_end_time") val hardEndTime: String?,
    @SerialName("working_days_only") val workingDaysOnly: Boolean,
)

/** Encode BlockingSchedule with this serializer (nested fields already do): required-nullable members stay on the wire as explicit null (R7) even when the Json omits nulls. */
object BlockingScheduleWire : JsonTransformingSerializer<BlockingSchedule>(BlockingSchedule.serializer()) {
    private val alwaysEmitted = listOf("hard_end_time")
    override fun transformSerialize(element: JsonElement): JsonElement =
        if (element is JsonObject) JsonObject(element + alwaysEmitted.filter { it !in element }.associateWith { JsonNull }) else element
}

/** UserManager restrictions set with DevicePolicyManager.addUserRestriction (true = restricted). */
@Serializable
data class DevicePolicyUserRestrictions(
    @SerialName("no_debugging_features") val noDebuggingFeatures: Boolean,
    @SerialName("no_install_unknown_sources") val noInstallUnknownSources: Boolean,
    @SerialName("no_install_apps") val noInstallApps: Boolean,
    @SerialName("no_factory_reset") val noFactoryReset: Boolean,
    @SerialName("no_safe_boot") val noSafeBoot: Boolean,
    @SerialName("no_add_user") val noAddUser: Boolean,
    @SerialName("no_config_date_time") val noConfigDateTime: Boolean,
    @SerialName("no_usb_file_transfer") val noUsbFileTransfer: Boolean,
    @SerialName("no_config_location") val noConfigLocation: Boolean,
)

@Serializable
data class DevicePolicyGlobalSettings(
    @SerialName("auto_time_required") val autoTimeRequired: Boolean,
    @SerialName("adb_enabled") val adbEnabled: Boolean,
    @SerialName("location_mode_high_accuracy") val locationModeHighAccuracy: Boolean,
)

@Serializable
data class DevicePolicySelfProtection(
    @SerialName("uninstall_blocked") val uninstallBlocked: Boolean,
    @SerialName("user_control_disabled") val userControlDisabled: Boolean,
    @SerialName("battery_optimisation_exempt") val batteryOptimisationExempt: Boolean,
)

@Serializable
data class DevicePolicyLocation(
    @SerialName("require_precise") val requirePrecise: Boolean,
    @SerialName("require_location_on") val requireLocationOn: Boolean,
    @SerialName("breadcrumbs_enabled") val breadcrumbsEnabled: Boolean,
    @SerialName("breadcrumb_interval_min") val breadcrumbIntervalMin: Int,
)

@Serializable
data class DevicePolicyStatusReport(
    @SerialName("on_events") val onEvents: List<String>,
    @SerialName("min_interval_min") val minIntervalMin: Int,
)

@Serializable
data class DevicePolicyIntegrity(
    @SerialName("play_integrity_required") val playIntegrityRequired: Boolean,
    @SerialName("refresh_h") val refreshH: Int,
    @SerialName("key_attestation_required") val keyAttestationRequired: Boolean,
) {
    override fun toString(): String = "DevicePolicyIntegrity(playIntegrityRequired=${playIntegrityRequired}, refreshH=${refreshH}, keyAttestationRequired=***)"
}

/** Device-owner policy (docs/24 s10.2). Applied by android:dpc; works offline once received. */
@Serializable
data class DevicePolicy(
    @SerialName("policy_version") val policyVersion: Long,
    @SerialName("lockdown_level") val lockdownLevel: String,
    @SerialName("generated_at") val generatedAt: String,
    @SerialName("user_restrictions") val userRestrictions: DevicePolicyUserRestrictions,
    @SerialName("global_settings") val globalSettings: DevicePolicyGlobalSettings,
    @SerialName("self_protection") val selfProtection: DevicePolicySelfProtection,
    @SerialName("permission_grants") val permissionGrants: List<PermissionGrant>,
    @SerialName("app_control") val appControl: AppControlPolicy,
    @Serializable(with = BlockingScheduleWire::class) @SerialName("schedule") val schedule: BlockingSchedule,
    @SerialName("location") val location: DevicePolicyLocation,
    @SerialName("status_report") val statusReport: DevicePolicyStatusReport,
    @SerialName("integrity") val integrity: DevicePolicyIntegrity,
)

@Serializable
data class EnrolDeviceResponse(
    @SerialName("device_id") val deviceId: Long,
    @SerialName("device_uuid") val deviceUuid: String,
    @SerialName("enrolled_at") val enrolledAt: String,
    @SerialName("lockdown_level") val lockdownLevel: String,
    @SerialName("trust_level") val trustLevel: String,
    @SerialName("policy") val policy: DevicePolicy,
    @SerialName("server_time") val serverTime: String,
)

// ---- Sync batch parts and errors ----

@Serializable
data class TimeAnchor(
    @SerialName("boot_count") val bootCount: Int,
    @SerialName("server_time") val serverTime: String,
    @SerialName("elapsed_ms") val elapsedMs: Long,
)

@Serializable
data class Resolution(
    @SerialName("client_uuid") val clientUuid: String,
    @SerialName("type") val type: String,
    @SerialName("resolution") val resolution: String,
    @SerialName("resolved_at") val resolvedAt: String,
)

@Serializable
data class RouteDayState(
    @SerialName("route_id") val routeId: Long,
    @SerialName("business_date") val businessDate: String,
    @SerialName("state") val state: String,
    @SerialName("planned") val planned: Boolean? = null,
    @SerialName("submit_cycle") val submitCycle: Int,
    @SerialName("submit_voided") val submitVoided: Boolean,
    @SerialName("submit_count_mismatch") val submitCountMismatch: Boolean? = null,
    @SerialName("logged_in_at") val loggedInAt: String? = null,
    @SerialName("sales_submitted_at") val salesSubmittedAt: String? = null,
    @SerialName("final_submitted_at") val finalSubmittedAt: String? = null,
    @SerialName("rows_awaited") val rowsAwaited: Int? = null,
    @SerialName("route_code") val routeCode: String? = null,
    @SerialName("route_name") val routeName: String? = null,
    @SerialName("assigned_user_id") val assignedUserId: Long? = null,
    @SerialName("acting_user_id") val actingUserId: Long? = null,
)

/** The server's view of one user and business date. */
@Serializable
data class ServerTotals(
    @SerialName("business_date") val businessDate: String,
    @SerialName("as_of") val asOf: String,
    @SerialName("by_type") val byType: Map<String, JsonElement>,
    @SerialName("money") val money: JsonElement,
)

@Serializable
data class ResolvedConfigValue(
    @SerialName("key") val key: String,
    @SerialName("value") val value: JsonElement,
    @SerialName("scope_type") val scopeType: String,
    @SerialName("scope_id") val scopeId: Long? = null,
    @SerialName("effective_from") val effectiveFrom: String?,
    @SerialName("effective_to") val effectiveTo: String? = null,
    @SerialName("config_version") val configVersion: Long? = null,
    @SerialName("requires_ack") val requiresAck: Boolean,
    @SerialName("bounds") val bounds: JsonElement? = null,
)

/** Encode ResolvedConfigValue with this serializer (nested fields already do): required-nullable members stay on the wire as explicit null (R7) even when the Json omits nulls. */
object ResolvedConfigValueWire : JsonTransformingSerializer<ResolvedConfigValue>(ResolvedConfigValue.serializer()) {
    private val alwaysEmitted = listOf("effective_from")
    override fun transformSerialize(element: JsonElement): JsonElement =
        if (element is JsonObject) JsonObject(element + alwaysEmitted.filter { it !in element }.associateWith { JsonNull }) else element
}

@Serializable
data class FieldError(
    @SerialName("pointer") val pointer: String,
    @SerialName("code") val code: String,
    @SerialName("message") val message: String? = null,
) {
    override fun toString(): String = "FieldError(pointer=${pointer}, code=***, message=${message})"
}

/** RFC 9457 problem details with Aron extension members. */
@Serializable
data class Problem(
    @SerialName("type") val type: String,
    @SerialName("title") val title: String,
    @SerialName("status") val status: Int,
    @SerialName("detail") val detail: String? = null,
    @SerialName("instance") val instance: String? = null,
    @SerialName("code") val code: String,
    @SerialName("request_id") val requestId: String,
    @SerialName("retryable") val retryable: Boolean? = null,
    @SerialName("retry_after_s") val retryAfterS: Int? = null,
    @SerialName("server_time") val serverTime: String? = null,
    @SerialName("message_key") val messageKey: String? = null,
    @SerialName("errors") val errors: List<FieldError>? = null,
    @SerialName("context") val context: Map<String, JsonElement>? = null,
) {
    override fun toString(): String = "Problem(type=${type}, title=${title}, status=${status}, detail=${detail}, instance=${instance}, code=***, requestId=${requestId}, retryable=${retryable}, retryAfterS=${retryAfterS}, serverTime=${serverTime}, messageKey=${messageKey}, errors=${errors}, context=${context})"
}

// ---- Sync batch ----

@Serializable
data class SyncBatchRequest(
    @SerialName("batch_uuid") val batchUuid: String,
    @SerialName("device_uuid") val deviceUuid: String,
    @SerialName("schema_version") val schemaVersion: Int,
    @SerialName("app_version") val appVersion: String,
    @SerialName("trigger") val trigger: String,
    @SerialName("sent_at_device") val sentAtDevice: String,
    @SerialName("pending_rows") val pendingRows: Int,
    @SerialName("time_anchors") val timeAnchors: List<TimeAnchor>,
    @SerialName("device_counts") val deviceCounts: Map<String, JsonElement>,
    @SerialName("device_money") val deviceMoney: Map<String, JsonElement>? = null,
    @SerialName("telemetry") val telemetry: JsonElement? = null,
    @SerialName("records") val records: List<JsonObject>,
)

@Serializable
data class SyncBatchSummary(
    @SerialName("accepted") val accepted: Int,
    @SerialName("duplicate") val duplicate: Int,
    @SerialName("rejected") val rejected: Int,
    @SerialName("quarantined") val quarantined: Int,
)

@Serializable
data class SyncBatchResponse(
    @SerialName("batch_uuid") val batchUuid: String,
    @SerialName("replayed") val replayed: Boolean,
    @SerialName("received_at") val receivedAt: String,
    @SerialName("acks") val acks: List<RecordAck>,
    @SerialName("summary") val summary: SyncBatchSummary,
    @SerialName("server_totals") val serverTotals: List<ServerTotals>,
    @SerialName("day_states") val dayStates: List<RouteDayState>,
    @SerialName("supervisor_day") val supervisorDay: JsonElement? = null,
    @SerialName("resolutions") val resolutions: List<Resolution>,
    @SerialName("hold_s") val holdS: Int,
    @SerialName("config_version") val configVersion: Long,
    @SerialName("bundle_version_current") val bundleVersionCurrent: String? = null,
    @SerialName("generation") val generation: String,
    @SerialName("directives") val directives: List<JsonElement>? = null,
)

@Serializable
data class RecordAck(
    @SerialName("client_uuid") val clientUuid: String,
    @SerialName("type") val type: String,
    @SerialName("status") val status: String,
    @SerialName("code") val code: String? = null,
    @SerialName("retryable") val retryable: Boolean? = null,
    @SerialName("message_key") val messageKey: String? = null,
    @SerialName("server_id") val serverId: Long? = null,
) {
    override fun toString(): String = "RecordAck(clientUuid=${clientUuid}, type=${type}, status=${status}, code=***, retryable=${retryable}, messageKey=${messageKey}, serverId=${serverId})"
}
