-- Generated by db/seed/gen_products.py from db/seed/sku_catalog.csv. Do not edit by hand.
-- Product tree (category > segment > brand > variant), SKUs and the five price types valid from 2026-01-01.

INSERT INTO app.product_node (level, name, sort) SELECT 'category', 'Cigarette', 1
  WHERE NOT EXISTS (SELECT 1 FROM app.product_node WHERE level = 'category' AND name = 'Cigarette');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'segment', p.id, 'Medium', 1 FROM app.product_node p WHERE p.level = 'category' AND p.name = 'Cigarette'
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'segment' AND c.parent_id = p.id AND c.name = 'Medium');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Maxim', 1 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Medium' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Maxim');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Maxim Regular', 1 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Maxim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Medium' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Maxim Regular');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Maxim Bolt', 3 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Maxim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Medium' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Maxim Bolt');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Maxim Wild Berry', 5 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Maxim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Medium' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Maxim Wild Berry');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Maxim Double Burst', 7 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Maxim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Medium' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Maxim Double Burst');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Maxim Prime', 9 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Maxim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Medium' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Maxim Prime');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'segment', p.id, 'Slim', 10 FROM app.product_node p WHERE p.level = 'category' AND p.name = 'Cigarette'
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'segment' AND c.parent_id = p.id AND c.name = 'Slim');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Avon', 10 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Slim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Avon');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Avon', 10 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Avon' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Slim' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Avon');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'ARIS', 11 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Slim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'ARIS');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'ARIS Apple', 11 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'ARIS' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Slim' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'ARIS Apple');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'ARIS Original', 12 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'ARIS' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Slim' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'ARIS Original');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'ARIS Strawberry', 13 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'ARIS' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Slim' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'ARIS Strawberry');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'segment', p.id, 'Low', 14 FROM app.product_node p WHERE p.level = 'category' AND p.name = 'Cigarette'
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'segment' AND c.parent_id = p.id AND c.name = 'Low');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Marise', 14 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Low' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Marise');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Marise Special Blend', 14 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Marise' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Marise Special Blend');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Black Diamond', 16 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Low' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Black Diamond');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Black Diamond Double Filter', 16 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Black Diamond' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Black Diamond Double Filter');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Black Diamond Advanced', 18 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Black Diamond' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Black Diamond Advanced');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Sunmoon', 20 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Low' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Sunmoon');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Sunmoon American blend', 20 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Sunmoon' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Sunmoon American blend');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Supreme', 22 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Low' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Supreme');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Supreme Signature', 22 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Supreme' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Supreme Signature');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Supreme', 24 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Supreme' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Supreme');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Supreme Style', 26 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Supreme' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Supreme Style');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Supreme Fresh Max', 28 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Supreme' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Low' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Supreme Fresh Max');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'ESSE', 30 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Slim' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'ESSE');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'ESSE Prime', 30 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'ESSE' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Slim' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'ESSE Prime');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'ESSE Change Mango', 31 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'ESSE' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Slim' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Cigarette'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'ESSE Change Mango');
INSERT INTO app.product_node (level, name, sort) SELECT 'category', 'Bidi', 2
  WHERE NOT EXISTS (SELECT 1 FROM app.product_node WHERE level = 'category' AND name = 'Bidi');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'segment', p.id, 'Bidi', 32 FROM app.product_node p WHERE p.level = 'category' AND p.name = 'Bidi'
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'segment' AND c.parent_id = p.id AND c.name = 'Bidi');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Special Abul Bidi', 32 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Special Abul Bidi');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Special Abul Bidi 25', 32 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Special Abul Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Bidi' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Special Abul Bidi 25');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Special Abul Bidi 12', 33 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Special Abul Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Bidi' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Special Abul Bidi 12');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Existing Abul Bidi/ 42 No. Abul Bidi', 34 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Existing Abul Bidi/ 42 No. Abul Bidi');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Existing Abul Bidi/ 42 No. Abul Bidi', 34 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Existing Abul Bidi/ 42 No. Abul Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Bidi' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Existing Abul Bidi/ 42 No. Abul Bidi');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Ananda Bidi', 35 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Ananda Bidi');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Ananda Bidi 25', 35 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Ananda Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Bidi' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Ananda Bidi 25');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Ananda Bidi 12', 36 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Ananda Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Bidi' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Ananda Bidi 12');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Abul Bidi Gold', 37 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Abul Bidi Gold');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Abul Bidi Gold', 37 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Abul Bidi Gold' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Bidi' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Abul Bidi Gold');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Abul Bidi Style', 38 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Bidi' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Abul Bidi Style');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Abul Bidi Style', 38 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Abul Bidi Style' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Bidi' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Bidi'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Abul Bidi Style');
INSERT INTO app.product_node (level, name, sort) SELECT 'category', 'Lighter', 3
  WHERE NOT EXISTS (SELECT 1 FROM app.product_node WHERE level = 'category' AND name = 'Lighter');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'segment', p.id, 'Lighter', 39 FROM app.product_node p WHERE p.level = 'category' AND p.name = 'Lighter'
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'segment' AND c.parent_id = p.id AND c.name = 'Lighter');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Aster', 39 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Lighter' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Lighter')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Aster');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Aster', 39 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Aster' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Lighter' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Lighter'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Aster');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'MAX', 40 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Lighter' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Lighter')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'MAX');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'MAX', 40 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'MAX' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Lighter' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Lighter'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'MAX');
INSERT INTO app.product_node (level, name, sort) SELECT 'category', 'Match', 4
  WHERE NOT EXISTS (SELECT 1 FROM app.product_node WHERE level = 'category' AND name = 'Match');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'segment', p.id, 'Match', 41 FROM app.product_node p WHERE p.level = 'category' AND p.name = 'Match'
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'segment' AND c.parent_id = p.id AND c.name = 'Match');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Flame Box', 41 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Match' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Match')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Flame Box');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Flame Box', 41 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Flame Box' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Match' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Match'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Flame Box');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'brand', p.id, 'Salmon', 42 FROM app.product_node p WHERE p.level = 'segment' AND p.name = 'Match' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Match')
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'brand' AND c.parent_id = p.id AND c.name = 'Salmon');
INSERT INTO app.product_node (level, parent_id, name, sort)
  SELECT 'variant', p.id, 'Salmon', 42 FROM app.product_node p WHERE p.level = 'brand' AND p.name = 'Salmon' AND p.parent_id = (SELECT id FROM app.product_node WHERE level = 'segment' AND name = 'Match' AND parent_id = (SELECT id FROM app.product_node WHERE level = 'category' AND name = 'Match'))
  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = 'variant' AND c.parent_id = p.id AND c.name = 'Salmon');

INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxR-10S', v.id, 'cigarette', 'Maxim Regular 10 (HLP)', 'MaxR-10S', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 1, 'active', 'MaxR-10S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Regular' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxR-10S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 7935), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxR-10S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxR-20S', v.id, 'cigarette', 'Maxim Regular 20 (HLP)', 'MaxR-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 2, 'active', 'MaxR-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Regular' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxR-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 7935), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxR-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxB-10S', v.id, 'cigarette', 'Maxim Bolt 10 (HLP)', 'MaxB-10S', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 3, 'active', 'MaxB-10S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Bolt' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxB-10S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 7935), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxB-10S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxB-20S', v.id, 'cigarette', 'Maxim Bolt 20 (HLP)', 'MaxB-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 4, 'active', 'MaxB-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Bolt' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxB-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 7935), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxB-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxWB-10S', v.id, 'cigarette', 'Maxim Wild Berry 10 (HLP)', 'MaxWB-10S', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 5, 'active', 'MaxWB-10S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Wild Berry' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxWB-10S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 7935), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxWB-10S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxWB-20S', v.id, 'cigarette', 'Maxim Wild Berry 20 (HLP)', 'MaxWB-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 6, 'active', 'MaxWB-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Wild Berry' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxWB-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 7935), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxWB-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxDB-20S_20HL', v.id, 'cigarette', 'Maxim Double Burst 20 (HLP)', 'MaxDB-20S 20HL', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 7, 'active', 'MaxDB-20S 20HL'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Double Burst' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxDB-20S_20HL');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 9125), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxDB-20S_20HL' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxDB-10S_10HL', v.id, 'cigarette', 'Maxim Double Burst 10 (HLP)', 'MaxDB-10S 10HL', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 8, 'active', 'MaxDB-10S 10HL'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Double Burst' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxDB-10S_10HL');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 0), ('cc', 0), ('distributor', 0), ('reporting', 0), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxDB-10S_10HL' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MaxPrime-20S_20HL', v.id, 'cigarette', 'Maxim Prime 20 (HLP)', 'MaxPrime-20S 20HL', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 9, 'active', 'MaxPrime-20S 20HL'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Maxim Prime' AND b.name = 'Maxim' AND s.name = 'Medium' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MaxPrime-20S_20HL');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9200), ('cc', 9200), ('distributor', 7935), ('reporting', 9200), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MaxPrime-20S_20HL' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'Avon-20S', v.id, 'cigarette', 'Avon 20 (HLP)', 'Avon-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 10, 'active', 'Avon-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Avon' AND b.name = 'Avon' AND s.name = 'Slim' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'Avon-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 7000), ('cc', 7000), ('distributor', 6945), ('reporting', 7000), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'Avon-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'ARIS-A-20s', v.id, 'cigarette', 'ARIS Apple 20 (HLP)', 'ARIS-A-20s', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 11, 'active', 'ARIS-A-20s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'ARIS Apple' AND b.name = 'ARIS' AND s.name = 'Slim' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'ARIS-A-20s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6445), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'ARIS-A-20s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'ARIS-O-20s', v.id, 'cigarette', 'ARIS Original 20 (HLP)', 'ARIS-O-20s', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 12, 'active', 'ARIS-O-20s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'ARIS Original' AND b.name = 'ARIS' AND s.name = 'Slim' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'ARIS-O-20s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6445), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'ARIS-O-20s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'ARIS-S-20s', v.id, 'cigarette', 'ARIS Strawberry 20 (HLP)', 'ARIS-S-20s', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 13, 'active', 'ARIS-S-20s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'ARIS Strawberry' AND b.name = 'ARIS' AND s.name = 'Slim' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'ARIS-S-20s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6445), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'ARIS-S-20s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MSB-10s', v.id, 'cigarette', 'Marise Special Blend 10 (HLP)', 'MSB-10s', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 14, 'active', 'MSB-10s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Marise Special Blend' AND b.name = 'Marise' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MSB-10s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MSB-10s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MSB-20s', v.id, 'cigarette', 'Marise Special Blend 20 (HLP)', 'MSB-20s', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 15, 'active', 'MSB-20s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Marise Special Blend' AND b.name = 'Marise' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MSB-20s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MSB-20s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'BDDF-10s', v.id, 'cigarette', 'Black Diamond Double Filter 10 (HLP)', 'BDDF-10s', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 16, 'active', 'BDDF-10s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Black Diamond Double Filter' AND b.name = 'Black Diamond' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'BDDF-10s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'BDDF-10s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'BDDF-20s', v.id, 'cigarette', 'Black Diamond Double Filter 20 (HLP)', 'BDDF-20s', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 17, 'active', 'BDDF-20s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Black Diamond Double Filter' AND b.name = 'Black Diamond' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'BDDF-20s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'BDDF-20s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'BDA-10s', v.id, 'cigarette', 'Black Diamond Advanced 10 (HLP)', 'BDA-10s', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 18, 'active', 'BDA-10s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Black Diamond Advanced' AND b.name = 'Black Diamond' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'BDA-10s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'BDA-10s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'BDA-20s', v.id, 'cigarette', 'Black Diamond Advanced 20 (HLP)', 'BDA-20s', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 19, 'active', 'BDA-20s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Black Diamond Advanced' AND b.name = 'Black Diamond' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'BDA-20s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'BDA-20s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SM-American-10s', v.id, 'cigarette', 'Sunmoon American blend 10 (HLP)', 'SM-American-10s', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 20, 'active', 'SM-American-10s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Sunmoon American blend' AND b.name = 'Sunmoon' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SM-American-10s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SM-American-10s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SM-American-20s', v.id, 'cigarette', 'Sunmoon American blend 20 (HLP)', 'SM-American-20s', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 21, 'active', 'SM-American-20s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Sunmoon American blend' AND b.name = 'Sunmoon' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SM-American-20s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SM-American-20s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SupSig-10S', v.id, 'cigarette', 'Supreme Signature 10 (HLP)', 'SupSig-10S', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 22, 'active', 'SupSig-10S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme Signature' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SupSig-10S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SupSig-10S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SupSig-20S', v.id, 'cigarette', 'Supreme Signature 20 (HLP)', 'SupSig-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 23, 'active', 'SupSig-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme Signature' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SupSig-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SupSig-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'Supreme-10S', v.id, 'cigarette', 'Supreme 10 (HLP)', 'Supreme-10S', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 24, 'active', 'Supreme-10S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'Supreme-10S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'Supreme-10S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'Supreme-20S', v.id, 'cigarette', 'Supreme 20 (HLP)', 'Supreme-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 25, 'active', 'Supreme-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'Supreme-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'Supreme-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SupSty-10S', v.id, 'cigarette', 'Supreme Style 10 (HLP)', 'SupSty-10S', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 26, 'active', 'SupSty-10S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme Style' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SupSty-10S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 0), ('cc', 0), ('distributor', 0), ('reporting', 0), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SupSty-10S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SupSty-20S', v.id, 'cigarette', 'Supreme Style 20 (HLP)', 'SupSty-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 27, 'active', 'SupSty-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme Style' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SupSty-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 0), ('cc', 0), ('distributor', 0), ('reporting', 0), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SupSty-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SupFM-10S', v.id, 'cigarette', 'Supreme Fresh Max 10 (HLP)', 'SupFM-10S', 'stick', 10, 'HLP',
         'stick', 'stick', 1, 28, 'active', 'SupFM-10S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme Fresh Max' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SupFM-10S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SupFM-10S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SupFM-20S', v.id, 'cigarette', 'Supreme Fresh Max 20 (HLP)', 'SupFM-20S', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 29, 'active', 'SupFM-20S'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Supreme Fresh Max' AND b.name = 'Supreme' AND s.name = 'Low' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SupFM-20S');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 6500), ('cc', 6500), ('distributor', 6500), ('reporting', 6500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SupFM-20S' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'EssP-20S_20HL', v.id, 'cigarette', 'ESSE Prime 20 (HLP)', 'EssP-20S 20HL', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 30, 'active', 'EssP-20S 20HL'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'ESSE Prime' AND b.name = 'ESSE' AND s.name = 'Slim' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'EssP-20S_20HL');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 9000), ('cc', 9000), ('distributor', 8920), ('reporting', 9000), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'EssP-20S_20HL' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'EssCM-20S_20HL', v.id, 'cigarette', 'ESSE Change Mango 20 (HLP)', 'EssCM-20S 20HL', 'stick', 20, 'HLP',
         'stick', 'stick', 1, 31, 'active', 'EssCM-20S 20HL'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'ESSE Change Mango' AND b.name = 'ESSE' AND s.name = 'Slim' AND c.name = 'Cigarette'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'EssCM-20S_20HL');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 11000), ('cc', 11000), ('distributor', 10920), ('reporting', 11000), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'EssCM-20S_20HL' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SAB-25s', v.id, 'bidi', 'Special Abul Bidi 25 25 (Soft Pack)', 'SAB-25s', 'stick', 25, 'Soft Pack',
         'stick', 'stick', 1, 32, 'active', 'SAB-25s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Special Abul Bidi 25' AND b.name = 'Special Abul Bidi' AND s.name = 'Bidi' AND c.name = 'Bidi'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SAB-25s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 880), ('cc', 880), ('distributor', 873), ('reporting', 880), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SAB-25s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SAB-12s', v.id, 'bidi', 'Special Abul Bidi 12 12 (Hard Pack)', 'SAB-12s', 'stick', 12, 'Hard Pack',
         'stick', 'stick', 1, 33, 'active', 'SAB-12s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Special Abul Bidi 12' AND b.name = 'Special Abul Bidi' AND s.name = 'Bidi' AND c.name = 'Bidi'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SAB-12s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 833), ('cc', 833), ('distributor', 826), ('reporting', 833), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SAB-12s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'EAB', v.id, 'bidi', 'Existing Abul Bidi/ 42 No. Abul Bidi 25 (Soft Pack)', 'EAB', 'stick', 25, 'Soft Pack',
         'stick', 'stick', 1, 34, 'active', 'EAB'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Existing Abul Bidi/ 42 No. Abul Bidi' AND b.name = 'Existing Abul Bidi/ 42 No. Abul Bidi' AND s.name = 'Bidi' AND c.name = 'Bidi'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'EAB');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 560), ('cc', 560), ('distributor', 556), ('reporting', 560), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'EAB' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'AB-25s', v.id, 'bidi', 'Ananda Bidi 25 25 (Soft Pack)', 'AB-25s', 'stick', 25, 'Soft Pack',
         'stick', 'stick', 1, 35, 'active', 'AB-25s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Ananda Bidi 25' AND b.name = 'Ananda Bidi' AND s.name = 'Bidi' AND c.name = 'Bidi'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'AB-25s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 800), ('cc', 800), ('distributor', 792), ('reporting', 800), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'AB-25s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'AB-12s', v.id, 'bidi', 'Ananda Bidi 12 12 (Hard Pack)', 'AB-12s', 'stick', 12, 'Hard Pack',
         'stick', 'stick', 1, 36, 'active', 'AB-12s'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Ananda Bidi 12' AND b.name = 'Ananda Bidi' AND s.name = 'Bidi' AND c.name = 'Bidi'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'AB-12s');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 750), ('cc', 750), ('distributor', 742), ('reporting', 750), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'AB-12s' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'ABG', v.id, 'bidi', 'Abul Bidi Gold 25 (Soft Pack)', 'ABG', 'stick', 25, 'Soft Pack',
         'stick', 'stick', 1, 37, 'active', 'ABG'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Abul Bidi Gold' AND b.name = 'Abul Bidi Gold' AND s.name = 'Bidi' AND c.name = 'Bidi'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'ABG');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 520), ('cc', 520), ('distributor', 515), ('reporting', 520), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'ABG' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'ABS', v.id, 'bidi', 'Abul Bidi Style 25 (Soft Pack)', 'ABS', 'stick', 25, 'Soft Pack',
         'stick', 'stick', 1, 38, 'active', 'ABS'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Abul Bidi Style' AND b.name = 'Abul Bidi Style' AND s.name = 'Bidi' AND c.name = 'Bidi'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'ABS');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 800), ('cc', 800), ('distributor', 792), ('reporting', 800), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'ABS' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'Aster', v.id, 'lighter', 'Aster 1 (Box)', 'Aster', 'piece', 1, 'Box',
         'piece', 'piece', 1, 39, 'active', 'Aster'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Aster' AND b.name = 'Aster' AND s.name = 'Lighter' AND c.name = 'Lighter'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'Aster');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 12500), ('cc', 12500), ('distributor', 12300), ('reporting', 12500), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'Aster' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'MAX', v.id, 'lighter', 'MAX 1 (Box)', 'Max', 'piece', 1, 'Box',
         'piece', 'piece', 1, 40, 'active', 'MAX'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'MAX' AND b.name = 'MAX' AND s.name = 'Lighter' AND c.name = 'Lighter'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'MAX');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 12000), ('cc', 12000), ('distributor', 11800), ('reporting', 12000), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'MAX' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'FB', v.id, 'match', 'Flame Box 1 (Dozen)', 'FB', 'dozen', 1, 'Dozen',
         'dozen', 'dozen', 1, 41, 'active', 'FB'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Flame Box' AND b.name = 'Flame Box' AND s.name = 'Match' AND c.name = 'Match'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'FB');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 28000), ('cc', 28000), ('distributor', 27500), ('reporting', 28000), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'FB' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,
                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)
  SELECT 'SL', v.id, 'match', 'Salmon 1 (Dozen)', 'SL', 'dozen', 1, 'Dozen',
         'dozen', 'dozen', 1, 42, 'active', 'SL'
    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id
    JOIN app.product_node c ON c.id = s.parent_id
   WHERE v.level = 'variant' AND v.name = 'Salmon' AND b.name = 'Salmon' AND s.name = 'Match' AND c.name = 'Match'
     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = 'SL');
INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)
  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES ('outlet', 19000), ('cc', 19000), ('distributor', 18667), ('reporting', 19000), ('nto', 0)) AS p(price_type, amount_mtk)
   WHERE s.code = 'SL' AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);
