#!/usr/bin/env python3
"""Writes db/seed/02_products.sql from db/seed/sku_catalog.csv (run from the repository root).

Prices are parsed as exact decimals and stored in milli-taka (7.935 Tk = 7,935 mtk). SKU codes with a space are
stored with '_' (contract Sku.code has no space; docs/requests/db-sku-code-spaces.md); the printed short_name and
external_ref keep the catalogue text. Every statement is INSERT ... WHERE NOT EXISTS, so a second run changes nothing.
"""
import csv
from decimal import Decimal

SRC, OUT = "db/seed/sku_catalog.csv", "db/seed/02_products.sql"
PRICE_COLUMNS = [("outlet", "price_outlet"), ("cc", "price_cc"), ("distributor", "price_distributor"),
                 ("reporting", "price_reporting"), ("nto", "price_nto")]
BASE_UNIT = {"cigarette": "stick", "bidi": "stick", "lighter": "piece", "match": "dozen"}


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def mtk(text):
    v = Decimal(text) * 1000
    assert v == v.to_integral_value(), text
    return int(v)


rows = list(csv.DictReader(open(SRC, encoding="utf-8")))
out = ["-- Generated by db/seed/gen_products.py from db/seed/sku_catalog.csv. Do not edit by hand.",
       "-- Product tree (category > segment > brand > variant), SKUs and the five price types valid from 2026-01-01.", ""]


def node(level, name, parent_level=None, parent_name=None, grand=None, sort=0):
    if parent_level is None:
        out.append(f"INSERT INTO app.product_node (level, name, sort) SELECT 'category', {q(name)}, {sort}\n"
                   f"  WHERE NOT EXISTS (SELECT 1 FROM app.product_node WHERE level = 'category' AND name = {q(name)});")
        return
    out.append(
        f"INSERT INTO app.product_node (level, parent_id, name, sort)\n"
        f"  SELECT '{level}', p.id, {q(name)}, {sort} FROM app.product_node p WHERE p.level = '{parent_level}' AND p.name = {q(parent_name)}"
        + (f" AND p.parent_id = (SELECT id FROM app.product_node WHERE level = '{grand[0]}' AND name = {q(grand[1])}"
           + (f" AND parent_id = (SELECT id FROM app.product_node WHERE level = '{grand[2]}' AND name = {q(grand[3])})" if len(grand) > 2 else "")
           + ")" if grand else "")
        + f"\n  AND NOT EXISTS (SELECT 1 FROM app.product_node c WHERE c.level = '{level}' AND c.parent_id = p.id AND c.name = {q(name)});")


seen = set()
for i, r in enumerate(rows, 1):
    cat, seg, brand, var = r["category"], r["segment"], r["brand"], r["variant"]
    if ("c", cat) not in seen:
        seen.add(("c", cat)); node("category", cat, sort=len([k for k in seen if k[0] == "c"]))
    if ("s", cat, seg) not in seen:
        seen.add(("s", cat, seg)); node("segment", seg, "category", cat, sort=i)
    if ("b", cat, seg, brand) not in seen:
        seen.add(("b", cat, seg, brand)); node("brand", brand, "segment", seg, ("category", cat), sort=i)
    if ("v", cat, seg, brand, var) not in seen:
        seen.add(("v", cat, seg, brand, var)); node("variant", var, "brand", brand, ("segment", seg, "category", cat), sort=i)

out.append("")
for i, r in enumerate(rows, 1):
    cat = r["category"].lower()
    code = r["sku_code"].strip().replace(" ", "_")
    pack = int(r["pack_size"])
    name = f"{r['variant']} {pack} ({r['pack_type']})"
    out.append(
        "INSERT INTO app.sku (code, variant_id, category_code, name, short_name, base_unit, base_per_pack, pack_type,\n"
        "                     entry_unit_default, report_unit, report_factor, sort, status, external_ref)\n"
        f"  SELECT {q(code)}, v.id, '{cat}', {q(name)}, {q(r['short_name'].strip())}, '{BASE_UNIT[cat]}', {pack}, {q(r['pack_type'])},\n"
        f"         '{BASE_UNIT[cat]}', '{BASE_UNIT[cat]}', 1, {i}, '{'active' if r['status'].strip() == '1' else 'inactive'}', {q(r['sku_code'].strip())}\n"
        f"    FROM app.product_node v JOIN app.product_node b ON b.id = v.parent_id JOIN app.product_node s ON s.id = b.parent_id\n"
        f"    JOIN app.product_node c ON c.id = s.parent_id\n"
        f"   WHERE v.level = 'variant' AND v.name = {q(r['variant'])} AND b.name = {q(r['brand'])} AND s.name = {q(r['segment'])} AND c.name = {q(r['category'])}\n"
        f"     AND NOT EXISTS (SELECT 1 FROM app.sku WHERE code = {q(code)});")
    values = ", ".join(f"('{pt}', {mtk(r[col])})" for pt, col in PRICE_COLUMNS)
    out.append(
        "INSERT INTO app.sku_price (sku_id, price_type, amount_mtk, per_base_qty, valid_from)\n"
        f"  SELECT s.id, p.price_type, p.amount_mtk, 1, DATE '2026-01-01' FROM app.sku s, (VALUES {values}) AS p(price_type, amount_mtk)\n"
        f"   WHERE s.code = {q(code)} AND NOT EXISTS (SELECT 1 FROM app.sku_price x WHERE x.sku_id = s.id AND x.price_type = p.price_type);")

open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(len(rows), "skus")
