#!/usr/bin/env python3
"""Profile the Apsis data dump (sales CSV + retailer list) and print a Markdown report.

Aggregates only: the report never prints outlet names, owners, phone numbers or coordinates.
Re-run it on the full Apsis dump (docs/11) to refresh docs/22 and to sanity-check the importer.

    pip install duckdb openpyxl
    python3 scripts/profile-apsis-data.py --sales sales.csv --retailers retailer_list.xlsx > profile.md

Expected sales columns:    date (d/m/yyyy), outlet_code, sku_id, sku_name, volume
Expected retailer columns: Wing, Division, Territory Code, Territory, Zone Code, Zone Name, Outlet Name,
  Owner Name, Contact Number, Route Code, Route, Outlet Code, Cluster Type, Cluster Name, Address, NID, TIN,
  Trade License, Latitude, Longitude, Geo Classification, Sub Channel, Created At, Updated At
  (the Excel export has an empty first row and an empty first column; both are skipped).
"""
import argparse
import csv
import os
import sys
import tempfile

import duckdb


def xlsx_to_csv(path, out_csv):
    import openpyxl
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    ws = wb.worksheets[0]
    with open(out_csv, "w", newline="") as f:
        w = csv.writer(f)
        for row in ws.iter_rows(values_only=True):
            w.writerow(row)


def table(con, title, sql, headers):
    rows = con.execute(sql).fetchall()
    print(f"\n### {title}\n")
    print("| " + " | ".join(headers) + " |")
    print("|" + "---|" * len(headers))
    for r in rows:
        print("| " + " | ".join("" if v is None else (f"{v:,.1f}" if isinstance(v, float) else str(v)) for v in r) + " |")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sales", required=True)
    ap.add_argument("--retailers", required=True, help=".xlsx or .csv")
    args = ap.parse_args()

    con = duckdb.connect()
    con.execute(
        f"""create table s as select strptime(date,'%d/%m/%Y')::date d, outlet_code, sku_id::int sku_id,
            sku_name, volume::double v from read_csv('{args.sales}', header=true, all_varchar=true)"""
    )

    tmp = None
    csv_path = args.retailers
    if csv_path.lower().endswith(".xlsx"):
        tmp = tempfile.mkdtemp()
        csv_path = os.path.join(tmp, "retailers.csv")
        xlsx_to_csv(args.retailers, csv_path)
    con.execute(
        f"""create table r as select * exclude(column00) from read_csv('{csv_path}', header=true, skip=1,
            all_varchar=true, strict_mode=false, null_padding=true)"""
    )
    con.execute(
        """create table r2 as select *, "Outlet Code" oc, try_cast("Latitude" as double) lat,
           try_cast("Longitude" as double) lon from r"""
    )

    print("# Apsis data profile (generated by scripts/profile-apsis-data.py)\n")
    print("## Sales file")
    table(con, "Totals", """select count(*), min(d), max(d), count(distinct d), count(distinct outlet_code),
        count(distinct sku_id), sum((v=0)::int), sum((v<0)::int), sum((v!=floor(v))::int) from s""",
          ["rows", "first day", "last day", "days with data", "distinct outlets", "distinct SKUs", "zero-volume rows", "negative rows", "fractional rows"])
    table(con, "By month", """select strftime(d,'%Y-%m'), count(distinct d), count(*), round(count(*)/count(distinct d)),
        count(distinct outlet_code) from s group by 1 order by 1""",
          ["month", "trading days", "rows", "rows/day", "outlets"])
    table(con, "Outlets with positive volume per day (days with >1000 rows)", """select strftime(d,'%Y-%m'), round(avg(c)), max(c)
        from (select d, count(distinct outlet_code) c from s where v>0 group by d having count(*)>1000) group by 1 order by 1""",
          ["month", "avg outlets/day", "peak outlets/day"])
    table(con, "Weekday pattern", """select dayname(d), count(distinct d), round(avg(c)) from
        (select d, count(distinct outlet_code) c from s where v>0 group by d) group by 1 order by 2 desc""",
          ["weekday", "days with data", "avg outlets/day"])
    table(con, "Calendar days with no (or near-no) data", """with a as (select unnest(generate_series(min(d),max(d),interval 1 day))::date d from s),
        c as (select d, count(*) n from s group by d)
        select a.d, dayname(a.d), coalesce(c.n,0) from a left join c using (d) where coalesce(c.n,0) < 1000 order by 1""",
          ["date", "weekday", "rows"])
    table(con, "Volume per line (sticks/pieces) quantiles", """select quantile_cont(v,[0,.5,.9,.99,.999,1]) from s where v>0""", ["quantiles 0/50/90/99/99.9/100"])
    table(con, "SKUs per outlet-day", """select quantile_cont(c,[.5,.9,.99,1]) from (select d,outlet_code,count(*) c from s group by 1,2)""", ["quantiles 50/90/99/100"])
    table(con, "Duplicate (date, outlet, SKU) rows", """select count(*) from (select 1 from s group by d,outlet_code,sku_id having count(*)>1)""", ["duplicate keys"])
    table(con, "Outlet codes in sales by length", """select length(outlet_code), count(distinct outlet_code) from s group by 1 order by 1""", ["length", "outlets"])
    table(con, "Outlet visit frequency (distinct days sold)", """select quantile_cont(c,[.1,.25,.5,.75,.9]) from (select outlet_code,count(distinct d) c from s where v>0 group by 1)""", ["quantiles 10/25/50/75/90"])
    table(con, "SKU list", """select sku_id, sku_name, count(*), count(distinct outlet_code), round(100.0*sum((v=0)::int)/count(*),1) from s group by 1,2 order by 1""",
          ["sku_id", "sku_name", "rows", "outlets", "% zero rows"])

    print("\n## Retailer list")
    table(con, "Totals", """select count(*), count(distinct "Outlet Code"), count(distinct "Wing"), count(distinct "Division"),
        count(distinct "Territory Code"), count(distinct "Zone Code"), count(distinct "Route Code") from r2""",
          ["rows", "distinct outlet codes", "wings", "divisions", "territories", "zones", "routes"])
    table(con, "Outlet-code shapes", """select case when oc ~ '^[0-9]+$' then 'digits' when oc ~ '^[0-9]+[A-Za-z]+[0-9]*$' then 'digits+letters' else 'other' end, count(*) from r2 group by 1 order by 2 desc""", ["shape", "outlets"])
    table(con, "Sub-channel", """select "Sub Channel", count(*) from r2 group by 1 order by 2 desc""", ["sub-channel", "outlets"])
    table(con, "Geo classification", """select "Geo Classification", count(*) from r2 group by 1 order by 2 desc""", ["geo class", "outlets"])
    table(con, "Cluster type", """select "Cluster Type", count(*) from r2 group by 1 order by 2 desc""", ["cluster type", "outlets"])
    table(con, "Outlets per route / routes per zone", """select (select quantile_cont(c,[0,.5,.9,.99,1]) from (select count(*) c from r2 group by "Route Code")),
        (select quantile_cont(c,[0,.5,1]) from (select count(distinct "Route Code") c from r2 group by "Zone Code"))""",
          ["outlets per route 0/50/90/99/100", "routes per zone 0/50/100"])
    table(con, "Field completeness", """select count("Contact Number"), count("Owner Name"), count("Address"), count("TIN"), count("Trade License"),
        count("Updated At"), sum(("NID"='123')::int) from r2""",
          ["phone", "owner", "address", "TIN", "trade licence", "updated_at", "NID = placeholder '123'"])
    table(con, "Creation date by month (bulk loads show as spikes)", """select substr("Created At",1,7), count(*) from r2 group by 1 order by 1""", ["month", "outlets"])

    print("\n## Coordinates")
    table(con, "Quality", """select count(*), sum((lat is null or lon is null)::int), sum((lat=0 or lon=0)::int),
        sum((lat is not null and not (lat between 20.5 and 26.7 and lon between 88.0 and 92.8))::int) from r2""",
          ["outlets", "missing", "zero", "outside Bangladesh box"])
    table(con, "Outlets sharing an exact point with another outlet", """select count(*), sum(c), max(c) from
        (select lat,lon,count(*) c from r2 where lat is not null group by 1,2 having count(*)>1)""",
          ["shared points", "outlets on them", "max on one point"])
    con.execute("""create table cells as select cast(floor(lat/0.0005) as bigint) cy, cast(floor(lon/0.0005) as bigint) cx, count(*) c
        from r2 where lat is not null group by 1,2""")
    table(con, "Density: outlets in the same ~55 m cell (0.0005 degrees)", """select
        round(100.0*sum(case when c>=2 then c else 0 end)/sum(c),1), round(100.0*sum(case when c>=6 then c else 0 end)/sum(c),1),
        round(100.0*sum(case when c>=21 then c else 0 end)/sum(c),1), max(c) from cells""",
          ["% outlets with company", "% with 5+ others", "% with 20+ others", "max in one cell"])

    print("\n## Join: sales outlets vs retailer list")
    table(con, "Coverage", """select count(*), sum((r2.oc is not null)::int), sum((r2.oc is null)::int)
        from (select distinct outlet_code from s) x left join (select distinct oc from r2) r2 on r2.oc = x.outlet_code""",
          ["sales outlets", "in retailer list", "not in list (closed/removed?)"])
    table(con, "Sales rows and volume on outlets missing from the list", """select count(*), sum(v) from s where outlet_code not in (select oc from r2)""", ["rows", "volume"])


if __name__ == "__main__":
    sys.exit(main())
