#!/bin/bash
# Vendors third-party agent skills into .claude/skills/ for Android and Azure work.
# Re-run to update to the latest upstream versions, then review and commit the diff.
#
#   android/skills               (Google, Apache-2.0)    official Android skills
#   Drjacky/claude-android-ninja (Apache-2.0)            Android architecture, Gradle, testing
#   microsoft/azure-skills       (Microsoft, MIT)        Azure workflows: plan, deploy, diagnose, reliability
#   MicrosoftDocs/Agent-Skills   (Microsoft, CC-BY-4.0)  Azure docs indexes, a curated subset
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
DEST="$REPO_ROOT/.claude/skills"
SOURCES="$DEST/SOURCES.md"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Android skills for TV, Wear, XR, Cast and Engage are skipped: not relevant to a phone app.
ANDROID_SKIP="leanback-to-compose-tv-migration wear-compose-m3 display-glasses-with-jetpack-compose-glimmer media3-cast-integration engage-sdk-integration"

# Azure docs skills that matter for a scalable, resilient mobile backend.
AZURE_DOCS="azure-well-architected azure-architecture azure-resiliency azure-front-door
azure-managed-redis azure-cosmos-db azure-sql-database azure-database-postgresql
azure-container-apps azure-kubernetes-service azure-app-service azure-functions
azure-api-management azure-service-bus azure-event-hubs azure-monitor azure-load-balancer
azure-chaos-studio azure-key-vault azure-notification-hubs"

clone() { git clone -q --depth 1 "https://github.com/$1" "$TMP/$2"; git -C "$TMP/$2" rev-parse --short HEAD; }

install_skill() {  # <source dir> <name>
  rm -rf "${DEST:?}/$2"
  cp -r "$1" "$DEST/$2"
}

mkdir -p "$DEST"
{
  echo "# Vendored skills"
  echo
  echo "Generated by \`scripts/update-agent-skills.sh\`. Do not edit these skills by hand; re-run the script."
  echo
  echo "| Source | Commit | Skills |"
  echo "|---|---|---|"
} > "$SOURCES"

# Google's official Android skills: nested by category, flattened by skill name.
sha=$(clone android/skills android)
names=()
while IFS= read -r skill_md; do
  dir=$(dirname "$skill_md"); name=$(basename "$dir")
  case " $ANDROID_SKIP " in *" $name "*) continue ;; esac
  install_skill "$dir" "$name"; names+=("$name")
done < <(find "$TMP/android" -name SKILL.md -not -path '*/.git/*' | sort)
echo "| [android/skills](https://github.com/android/skills) | $sha | ${names[*]} |" >> "$SOURCES"

# claude-android-ninja: the repo root is the skill.
sha=$(clone Drjacky/claude-android-ninja android-ninja)
rm -rf "$TMP/android-ninja/.git" "$TMP/android-ninja/claude-android-ninja.png"
install_skill "$TMP/android-ninja" claude-android-ninja
echo "| [Drjacky/claude-android-ninja](https://github.com/Drjacky/claude-android-ninja) | $sha | claude-android-ninja |" >> "$SOURCES"

# Microsoft's Azure skills plugin: skills only. Its MCP server is configured in .mcp.json;
# its telemetry hooks are intentionally not installed.
sha=$(clone microsoft/azure-skills azure-skills)
names=()
for dir in "$TMP"/azure-skills/skills/*/; do
  name=$(basename "$dir"); install_skill "$dir" "$name"; names+=("$name")
done
echo "| [microsoft/azure-skills](https://github.com/microsoft/azure-skills) | $sha | ${names[*]} |" >> "$SOURCES"

# Microsoft Learn docs skills: curated subset. azure-skills wins on any name clash.
sha=$(clone MicrosoftDocs/Agent-Skills azure-docs)
names=()
for name in $AZURE_DOCS; do
  if [ -d "$TMP/azure-skills/skills/$name" ]; then continue; fi
  install_skill "$TMP/azure-docs/skills/$name" "$name"; names+=("$name")
done
echo "| [MicrosoftDocs/Agent-Skills](https://github.com/MicrosoftDocs/Agent-Skills) | $sha | ${names[*]} |" >> "$SOURCES"

echo "Skills updated. Review with: git status .claude/skills"
