#!/usr/bin/env python3
"""Generate small, readable slices of contract/openapi.yaml into contract/slices/ (generated, never edit).

    python3 tools/slice-contract.py            # (re)generate
    python3 tools/slice-contract.py --check    # exit 1 if contract/slices is out of date

contract/slices/INDEX.md lists every schema and operation with its size. Lanes read the one slice they need
instead of the 553 KB contract. The contract stays the only source of truth (docs/26 s2).
"""
import os
import sys
import yaml

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
src = os.path.join(root, 'contract', 'openapi.yaml')
out = os.path.join(root, 'contract', 'slices')
doc = yaml.safe_load(open(src, encoding='utf-8'))


def dump(o):
    return yaml.safe_dump(o, sort_keys=False, allow_unicode=True, width=110)


files = {}
index = ['# Contract slices (generated by tools/slice-contract.py; do not edit)\n',
         f"Source: contract/openapi.yaml, version {doc.get('info', {}).get('version')}.\n"]
schemas = doc.get('components', {}).get('schemas', {})
index.append(f'\n## Schemas ({len(schemas)})\n')
for name, sch in schemas.items():
    body = dump({name: sch})
    files[f'schemas/{name}.yaml'] = body
    index.append(f'- `schemas/{name}.yaml` ({len(body)} B)')
ops = []
for path, item in doc.get('paths', {}).items():
    for method, op in item.items():
        if method not in ('get', 'post', 'put', 'patch', 'delete', 'head'):
            continue
        opid = op.get('operationId') or (method + path).replace('/', '_').replace('{', '').replace('}', '')
        body = dump({'path': path, 'method': method, **({'parameters': item['parameters']} if 'parameters' in item else {}), 'operation': op})
        files[f'operations/{opid}.yaml'] = body
        ops.append((opid, method.upper(), path, len(body)))
index.append(f'\n## Operations ({len(ops)})\n')
for opid, m, p, n in ops:
    index.append(f'- `operations/{opid}.yaml`  {m} {p} ({n} B)')
for key in ('parameters', 'responses', 'securitySchemes', 'requestBodies', 'headers', 'examples'):
    sect = doc.get('components', {}).get(key)
    if sect:
        files[f'components-{key}.yaml'] = dump({key: sect})
        index.append(f'\n- `components-{key}.yaml` ({len(files[f"components-{key}.yaml"])} B)')
files['INDEX.md'] = '\n'.join(index) + '\n'

if '--check' in sys.argv:
    bad = []
    for rel, body in files.items():
        p = os.path.join(out, rel)
        if not os.path.exists(p) or open(p, encoding='utf-8').read() != body:
            bad.append(rel)
    if os.path.isdir(out):
        for dp, _, fs in os.walk(out):
            for f in fs:
                rel = os.path.relpath(os.path.join(dp, f), out).replace(os.sep, '/')
                if rel not in files:
                    bad.append(rel)
    if bad:
        print('contract/slices is out of date; run python3 tools/slice-contract.py. Differences:', bad[:10])
        sys.exit(1)
    print('contract/slices is up to date')
    sys.exit(0)

for rel, body in files.items():
    p = os.path.join(out, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, 'w', encoding='utf-8').write(body)
print(f'wrote {len(files)} files, {sum(len(b) for b in files.values())} bytes')
